/*-
 * ‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾
 * Autonomic Proprietary 1.0
 * ——————————————————————————————————————————————————————————————————————————————
 * Copyright (C) 2020 Autonomic, LLC - All rights reserved
 * ——————————————————————————————————————————————————————————————————————————————
 * Proprietary and confidential.
 *
 * NOTICE:  All information contained herein is, and remains the property of
 * Autonomic, LLC and its suppliers, if any.  The intellectual and technical
 * concepts contained herein are proprietary to Autonomic, LLC and its suppliers
 * and may be covered by U.S. and Foreign Patents, patents in process, and are
 * protected by trade secret or copyright law. Dissemination of this information
 * or reproduction of this material is strictly forbidden unless prior written
 * permission is obtained from Autonomic, LLC.
 *
 * Unauthorized copy of this file, via any medium is strictly prohibited.
 * ______________________________________________________________________________
 */
// Code generated by protoc-gen-go. DO NOT EDIT.
// source: autonomic/ext/telemetry/signal.proto

package telemetry

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Signal struct {
	// Types that are valid to be assigned to Signal:
	//	*Signal_WksSignal
	//	*Signal_StringSignal
	Signal               isSignal_Signal `protobuf_oneof:"signal"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Signal) Reset()         { *m = Signal{} }
func (m *Signal) String() string { return proto.CompactTextString(m) }
func (*Signal) ProtoMessage()    {}
func (*Signal) Descriptor() ([]byte, []int) {
	return fileDescriptor_728dd41906f24e48, []int{0}
}

func (m *Signal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Signal.Unmarshal(m, b)
}
func (m *Signal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Signal.Marshal(b, m, deterministic)
}
func (m *Signal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Signal.Merge(m, src)
}
func (m *Signal) XXX_Size() int {
	return xxx_messageInfo_Signal.Size(m)
}
func (m *Signal) XXX_DiscardUnknown() {
	xxx_messageInfo_Signal.DiscardUnknown(m)
}

var xxx_messageInfo_Signal proto.InternalMessageInfo

type isSignal_Signal interface {
	isSignal_Signal()
}

type Signal_WksSignal struct {
	WksSignal WellKnownSignal `protobuf:"varint,1,opt,name=wks_signal,json=wksSignal,proto3,enum=autonomic.ext.telemetry.signal.WellKnownSignal,oneof"`
}

type Signal_StringSignal struct {
	StringSignal string `protobuf:"bytes,2,opt,name=string_signal,json=stringSignal,proto3,oneof"`
}

func (*Signal_WksSignal) isSignal_Signal() {}

func (*Signal_StringSignal) isSignal_Signal() {}

func (m *Signal) GetSignal() isSignal_Signal {
	if m != nil {
		return m.Signal
	}
	return nil
}

func (m *Signal) GetWksSignal() WellKnownSignal {
	if x, ok := m.GetSignal().(*Signal_WksSignal); ok {
		return x.WksSignal
	}
	return WellKnownSignal_UNKNOWN_SIGNAL
}

func (m *Signal) GetStringSignal() string {
	if x, ok := m.GetSignal().(*Signal_StringSignal); ok {
		return x.StringSignal
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Signal) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Signal_WksSignal)(nil),
		(*Signal_StringSignal)(nil),
	}
}

func init() {
	proto.RegisterType((*Signal)(nil), "autonomic.ext.telemetry.signal.Signal")
}

func init() {
	proto.RegisterFile("autonomic/ext/telemetry/signal.proto", fileDescriptor_728dd41906f24e48)
}

var fileDescriptor_728dd41906f24e48 = []byte{
	// 253 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x49, 0x2c, 0x2d, 0xc9,
	0xcf, 0xcb, 0xcf, 0xcd, 0x4c, 0xd6, 0x4f, 0xad, 0x28, 0xd1, 0x2f, 0x49, 0xcd, 0x49, 0xcd, 0x4d,
	0x2d, 0x29, 0xaa, 0xd4, 0x2f, 0xce, 0x4c, 0xcf, 0x4b, 0xcc, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9,
	0x17, 0x92, 0x83, 0xab, 0xd2, 0x4b, 0xad, 0x28, 0xd1, 0x83, 0xab, 0xd2, 0x83, 0xa8, 0x92, 0x32,
	0xc0, 0x65, 0x4a, 0x79, 0x6a, 0x4e, 0x4e, 0x7c, 0x76, 0x5e, 0x7e, 0x79, 0x5e, 0x3c, 0x44, 0x69,
	0x31, 0xc4, 0x44, 0xa5, 0x6e, 0x46, 0x2e, 0xb6, 0x60, 0xb0, 0x88, 0x50, 0x00, 0x17, 0x57, 0x79,
	0x76, 0x31, 0x54, 0x5e, 0x82, 0x51, 0x81, 0x51, 0x83, 0xcf, 0x48, 0x5f, 0x0f, 0xbf, 0x8d, 0x7a,
	0xe1, 0xa9, 0x39, 0x39, 0xde, 0x20, 0x73, 0x21, 0x86, 0x78, 0x30, 0x04, 0x71, 0x96, 0x67, 0x17,
	0x43, 0x4d, 0x54, 0xe5, 0xe2, 0x2d, 0x2e, 0x29, 0xca, 0xcc, 0x4b, 0x87, 0x19, 0xca, 0xa4, 0xc0,
	0xa8, 0xc1, 0xe9, 0xc1, 0x10, 0xc4, 0x03, 0x11, 0x86, 0x28, 0x73, 0xe2, 0xe0, 0x62, 0x83, 0xc8,
	0x3b, 0xf5, 0x30, 0x72, 0x29, 0x25, 0xe7, 0xe7, 0x12, 0xb0, 0xd4, 0x89, 0x1b, 0xa2, 0x31, 0x00,
	0xe4, 0x83, 0x00, 0xc6, 0x28, 0xbf, 0xf4, 0xcc, 0x92, 0x8c, 0xd2, 0x24, 0xbd, 0xe4, 0xfc, 0x5c,
	0x7d, 0xb8, 0x4e, 0xdd, 0xc4, 0x4c, 0x50, 0x18, 0xa4, 0x16, 0xe5, 0x25, 0xe6, 0xe8, 0x82, 0xfd,
	0x5a, 0xac, 0x5f, 0x5c, 0x94, 0xac, 0x9f, 0x9b, 0x98, 0x99, 0xa7, 0x0f, 0xe6, 0xeb, 0xe3, 0x08,
	0xac, 0x1f, 0x8c, 0x8c, 0x8b, 0x98, 0x98, 0x1d, 0x43, 0x43, 0x92, 0xd8, 0xc0, 0xea, 0x8c, 0x01,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x5c, 0xa8, 0x73, 0x13, 0x9d, 0x01, 0x00, 0x00,
}
