/*-
 * ‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾
 * Autonomic Proprietary 1.0
 * ——————————————————————————————————————————————————————————————————————————————
 * Copyright (C) 2020 Autonomic, LLC - All rights reserved
 * ——————————————————————————————————————————————————————————————————————————————
 * Proprietary and confidential.
 *
 * NOTICE:  All information contained herein is, and remains the property of
 * Autonomic, LLC and its suppliers, if any.  The intellectual and technical
 * concepts contained herein are proprietary to Autonomic, LLC and its suppliers
 * and may be covered by U.S. and Foreign Patents, patents in process, and are
 * protected by trade secret or copyright law. Dissemination of this information
 * or reproduction of this material is strictly forbidden unless prior written
 * permission is obtained from Autonomic, LLC.
 *
 * Unauthorized copy of this file, via any medium is strictly prohibited.
 * ______________________________________________________________________________
 */
// Code generated by protoc-gen-go. DO NOT EDIT.
// source: autonomic/ext/command/errors/command_execution.proto

package errors

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The component where the failure occurred
type CommandExecutionFailure_ComponentSystem int32

const (
	CommandExecutionFailure_UNKNOWN_COMPONENT_SYSTEM CommandExecutionFailure_ComponentSystem = 0
	CommandExecutionFailure_COOLING_SYSTEM           CommandExecutionFailure_ComponentSystem = 1
	CommandExecutionFailure_MOTOR                    CommandExecutionFailure_ComponentSystem = 2
	CommandExecutionFailure_DOOR                     CommandExecutionFailure_ComponentSystem = 3
	CommandExecutionFailure_ANTI_THEFT_SYSTEM        CommandExecutionFailure_ComponentSystem = 4
)

var CommandExecutionFailure_ComponentSystem_name = map[int32]string{
	0: "UNKNOWN_COMPONENT_SYSTEM",
	1: "COOLING_SYSTEM",
	2: "MOTOR",
	3: "DOOR",
	4: "ANTI_THEFT_SYSTEM",
}

var CommandExecutionFailure_ComponentSystem_value = map[string]int32{
	"UNKNOWN_COMPONENT_SYSTEM": 0,
	"COOLING_SYSTEM":           1,
	"MOTOR":                    2,
	"DOOR":                     3,
	"ANTI_THEFT_SYSTEM":        4,
}

func (x CommandExecutionFailure_ComponentSystem) String() string {
	return proto.EnumName(CommandExecutionFailure_ComponentSystem_name, int32(x))
}

func (CommandExecutionFailure_ComponentSystem) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_597ef42e6d76d889, []int{0, 0}
}

type CommandFailureCause_CommandContentViolation int32

const (
	CommandFailureCause_UNKNOWN_CONTENT_VIOLATION CommandFailureCause_CommandContentViolation = 0
	// Command is unknown
	CommandFailureCause_UNKNOWN_COMMAND CommandFailureCause_CommandContentViolation = 1
	// Command contained illegal (read-only) content
	CommandFailureCause_ILLEGAL_COMMAND_CONTENT CommandFailureCause_CommandContentViolation = 2
	// Command contained invalid content
	CommandFailureCause_INVALID_COMMAND_CONTENT CommandFailureCause_CommandContentViolation = 3
)

var CommandFailureCause_CommandContentViolation_name = map[int32]string{
	0: "UNKNOWN_CONTENT_VIOLATION",
	1: "UNKNOWN_COMMAND",
	2: "ILLEGAL_COMMAND_CONTENT",
	3: "INVALID_COMMAND_CONTENT",
}

var CommandFailureCause_CommandContentViolation_value = map[string]int32{
	"UNKNOWN_CONTENT_VIOLATION": 0,
	"UNKNOWN_COMMAND":           1,
	"ILLEGAL_COMMAND_CONTENT":   2,
	"INVALID_COMMAND_CONTENT":   3,
}

func (x CommandFailureCause_CommandContentViolation) String() string {
	return proto.EnumName(CommandFailureCause_CommandContentViolation_name, int32(x))
}

func (CommandFailureCause_CommandContentViolation) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_597ef42e6d76d889, []int{2, 0}
}

type CommandFailureCause_TargetViolation int32

const (
	CommandFailureCause_UNKNOWN_TARGET_VIOLATION CommandFailureCause_TargetViolation = 0
	// Command was issued to an invalid target (e.g. component)
	CommandFailureCause_INVALID_TARGET CommandFailureCause_TargetViolation = 1
)

var CommandFailureCause_TargetViolation_name = map[int32]string{
	0: "UNKNOWN_TARGET_VIOLATION",
	1: "INVALID_TARGET",
}

var CommandFailureCause_TargetViolation_value = map[string]int32{
	"UNKNOWN_TARGET_VIOLATION": 0,
	"INVALID_TARGET":           1,
}

func (x CommandFailureCause_TargetViolation) String() string {
	return proto.EnumName(CommandFailureCause_TargetViolation_name, int32(x))
}

func (CommandFailureCause_TargetViolation) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_597ef42e6d76d889, []int{2, 1}
}

type CommandFailureCause_ComponentError int32

const (
	CommandFailureCause_UNKNOWN_COMPONENT_ERROR CommandFailureCause_ComponentError = 0
	// Command encountered an internal error in a component
	CommandFailureCause_INTERNAL_COMPONENT_ERROR CommandFailureCause_ComponentError = 1
	// Command encountered a memory error in a component
	CommandFailureCause_MEMORY_ERROR CommandFailureCause_ComponentError = 2
	// Command encountered an out of memory error in a component
	CommandFailureCause_OUT_OF_MEMORY_ERROR CommandFailureCause_ComponentError = 3
)

var CommandFailureCause_ComponentError_name = map[int32]string{
	0: "UNKNOWN_COMPONENT_ERROR",
	1: "INTERNAL_COMPONENT_ERROR",
	2: "MEMORY_ERROR",
	3: "OUT_OF_MEMORY_ERROR",
}

var CommandFailureCause_ComponentError_value = map[string]int32{
	"UNKNOWN_COMPONENT_ERROR":  0,
	"INTERNAL_COMPONENT_ERROR": 1,
	"MEMORY_ERROR":             2,
	"OUT_OF_MEMORY_ERROR":      3,
}

func (x CommandFailureCause_ComponentError) String() string {
	return proto.EnumName(CommandFailureCause_ComponentError_name, int32(x))
}

func (CommandFailureCause_ComponentError) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_597ef42e6d76d889, []int{2, 2}
}

type CommandFailureCause_CommunicationError int32

const (
	CommandFailureCause_UNKNOWN_COMMUNICATION_ERROR CommandFailureCause_CommunicationError = 0
	// Command encountered an error establishing a connection
	CommandFailureCause_CONNECTION_ESTABLISHMENT_ERROR CommandFailureCause_CommunicationError = 1
	// Command encountered a connection timeout error
	CommandFailureCause_CONNECTION_TIMEOUT_ERROR CommandFailureCause_CommunicationError = 2
	// Command encountered a communication error by the server
	CommandFailureCause_SERVER_ERROR CommandFailureCause_CommunicationError = 3
)

var CommandFailureCause_CommunicationError_name = map[int32]string{
	0: "UNKNOWN_COMMUNICATION_ERROR",
	1: "CONNECTION_ESTABLISHMENT_ERROR",
	2: "CONNECTION_TIMEOUT_ERROR",
	3: "SERVER_ERROR",
}

var CommandFailureCause_CommunicationError_value = map[string]int32{
	"UNKNOWN_COMMUNICATION_ERROR":    0,
	"CONNECTION_ESTABLISHMENT_ERROR": 1,
	"CONNECTION_TIMEOUT_ERROR":       2,
	"SERVER_ERROR":                   3,
}

func (x CommandFailureCause_CommunicationError) String() string {
	return proto.EnumName(CommandFailureCause_CommunicationError_name, int32(x))
}

func (CommandFailureCause_CommunicationError) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_597ef42e6d76d889, []int{2, 3}
}

// A command for which all preconditions are satisfied, but one or more errors cause the command
// to fail on the device. This message allows the device to state which component failed, and
// oem-specific information about the failure, which can then be handed by the cloud platfrom
// to calling applications.
//
// Note: this file is imported directly by the parent file command_error_data.proto.
//
type CommandExecutionFailure struct {
	ComponentSystem CommandExecutionFailure_ComponentSystem `protobuf:"varint,1,opt,name=component_system,json=componentSystem,proto3,enum=autonomic.ext.command.errors.CommandExecutionFailure_ComponentSystem" json:"component_system,omitempty"`
	// oem error code (opaque to au)
	OemErrorCode int32 `protobuf:"varint,2,opt,name=oem_error_code,json=oemErrorCode,proto3" json:"oem_error_code,omitempty"`
	// oem error context (opaque to au)
	OemErrorContext string `protobuf:"bytes,3,opt,name=oem_error_context,json=oemErrorContext,proto3" json:"oem_error_context,omitempty"`
	// Any component state changes as a result of the command execution attempt
	// (may not necessarily be the same component as expressed in component_system)
	ComponentStateChanges *PostCommandExecutionComponentStateChanges `protobuf:"bytes,4,opt,name=component_state_changes,json=componentStateChanges,proto3" json:"component_state_changes,omitempty"`
	// one or more reasons why the command failed
	CommandFailureCause  []*CommandFailureCause `protobuf:"bytes,5,rep,name=command_failure_cause,json=commandFailureCause,proto3" json:"command_failure_cause,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *CommandExecutionFailure) Reset()         { *m = CommandExecutionFailure{} }
func (m *CommandExecutionFailure) String() string { return proto.CompactTextString(m) }
func (*CommandExecutionFailure) ProtoMessage()    {}
func (*CommandExecutionFailure) Descriptor() ([]byte, []int) {
	return fileDescriptor_597ef42e6d76d889, []int{0}
}

func (m *CommandExecutionFailure) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandExecutionFailure.Unmarshal(m, b)
}
func (m *CommandExecutionFailure) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandExecutionFailure.Marshal(b, m, deterministic)
}
func (m *CommandExecutionFailure) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandExecutionFailure.Merge(m, src)
}
func (m *CommandExecutionFailure) XXX_Size() int {
	return xxx_messageInfo_CommandExecutionFailure.Size(m)
}
func (m *CommandExecutionFailure) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandExecutionFailure.DiscardUnknown(m)
}

var xxx_messageInfo_CommandExecutionFailure proto.InternalMessageInfo

func (m *CommandExecutionFailure) GetComponentSystem() CommandExecutionFailure_ComponentSystem {
	if m != nil {
		return m.ComponentSystem
	}
	return CommandExecutionFailure_UNKNOWN_COMPONENT_SYSTEM
}

func (m *CommandExecutionFailure) GetOemErrorCode() int32 {
	if m != nil {
		return m.OemErrorCode
	}
	return 0
}

func (m *CommandExecutionFailure) GetOemErrorContext() string {
	if m != nil {
		return m.OemErrorContext
	}
	return ""
}

func (m *CommandExecutionFailure) GetComponentStateChanges() *PostCommandExecutionComponentStateChanges {
	if m != nil {
		return m.ComponentStateChanges
	}
	return nil
}

func (m *CommandExecutionFailure) GetCommandFailureCause() []*CommandFailureCause {
	if m != nil {
		return m.CommandFailureCause
	}
	return nil
}

// A component state expresses the change of state of a component after
// a command execution has been attempted on a vehicle or device.
type PostCommandExecutionComponentStateChanges struct {
	// One or more hardware component states which changed as a result
	// of the command execution attempt
	HardwareStateChange  []*HardwareState `protobuf:"bytes,1,rep,name=hardware_state_change,json=hardwareStateChange,proto3" json:"hardware_state_change,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *PostCommandExecutionComponentStateChanges) Reset() {
	*m = PostCommandExecutionComponentStateChanges{}
}
func (m *PostCommandExecutionComponentStateChanges) String() string { return proto.CompactTextString(m) }
func (*PostCommandExecutionComponentStateChanges) ProtoMessage()    {}
func (*PostCommandExecutionComponentStateChanges) Descriptor() ([]byte, []int) {
	return fileDescriptor_597ef42e6d76d889, []int{1}
}

func (m *PostCommandExecutionComponentStateChanges) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostCommandExecutionComponentStateChanges.Unmarshal(m, b)
}
func (m *PostCommandExecutionComponentStateChanges) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostCommandExecutionComponentStateChanges.Marshal(b, m, deterministic)
}
func (m *PostCommandExecutionComponentStateChanges) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostCommandExecutionComponentStateChanges.Merge(m, src)
}
func (m *PostCommandExecutionComponentStateChanges) XXX_Size() int {
	return xxx_messageInfo_PostCommandExecutionComponentStateChanges.Size(m)
}
func (m *PostCommandExecutionComponentStateChanges) XXX_DiscardUnknown() {
	xxx_messageInfo_PostCommandExecutionComponentStateChanges.DiscardUnknown(m)
}

var xxx_messageInfo_PostCommandExecutionComponentStateChanges proto.InternalMessageInfo

func (m *PostCommandExecutionComponentStateChanges) GetHardwareStateChange() []*HardwareState {
	if m != nil {
		return m.HardwareStateChange
	}
	return nil
}

// Well known failure causes for a command
type CommandFailureCause struct {
	// Types that are valid to be assigned to Type:
	//	*CommandFailureCause_CommandContentViolation_
	//	*CommandFailureCause_TargetViolation_
	//	*CommandFailureCause_ComponentError_
	//	*CommandFailureCause_CommunicationError_
	Type                 isCommandFailureCause_Type `protobuf_oneof:"type"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *CommandFailureCause) Reset()         { *m = CommandFailureCause{} }
func (m *CommandFailureCause) String() string { return proto.CompactTextString(m) }
func (*CommandFailureCause) ProtoMessage()    {}
func (*CommandFailureCause) Descriptor() ([]byte, []int) {
	return fileDescriptor_597ef42e6d76d889, []int{2}
}

func (m *CommandFailureCause) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandFailureCause.Unmarshal(m, b)
}
func (m *CommandFailureCause) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandFailureCause.Marshal(b, m, deterministic)
}
func (m *CommandFailureCause) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandFailureCause.Merge(m, src)
}
func (m *CommandFailureCause) XXX_Size() int {
	return xxx_messageInfo_CommandFailureCause.Size(m)
}
func (m *CommandFailureCause) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandFailureCause.DiscardUnknown(m)
}

var xxx_messageInfo_CommandFailureCause proto.InternalMessageInfo

type isCommandFailureCause_Type interface {
	isCommandFailureCause_Type()
}

type CommandFailureCause_CommandContentViolation_ struct {
	CommandContentViolation CommandFailureCause_CommandContentViolation `protobuf:"varint,1,opt,name=command_content_violation,json=commandContentViolation,proto3,enum=autonomic.ext.command.errors.CommandFailureCause_CommandContentViolation,oneof"`
}

type CommandFailureCause_TargetViolation_ struct {
	TargetViolation CommandFailureCause_TargetViolation `protobuf:"varint,2,opt,name=target_violation,json=targetViolation,proto3,enum=autonomic.ext.command.errors.CommandFailureCause_TargetViolation,oneof"`
}

type CommandFailureCause_ComponentError_ struct {
	ComponentError CommandFailureCause_ComponentError `protobuf:"varint,3,opt,name=component_error,json=componentError,proto3,enum=autonomic.ext.command.errors.CommandFailureCause_ComponentError,oneof"`
}

type CommandFailureCause_CommunicationError_ struct {
	CommunicationError CommandFailureCause_CommunicationError `protobuf:"varint,4,opt,name=communication_error,json=communicationError,proto3,enum=autonomic.ext.command.errors.CommandFailureCause_CommunicationError,oneof"`
}

func (*CommandFailureCause_CommandContentViolation_) isCommandFailureCause_Type() {}

func (*CommandFailureCause_TargetViolation_) isCommandFailureCause_Type() {}

func (*CommandFailureCause_ComponentError_) isCommandFailureCause_Type() {}

func (*CommandFailureCause_CommunicationError_) isCommandFailureCause_Type() {}

func (m *CommandFailureCause) GetType() isCommandFailureCause_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *CommandFailureCause) GetCommandContentViolation() CommandFailureCause_CommandContentViolation {
	if x, ok := m.GetType().(*CommandFailureCause_CommandContentViolation_); ok {
		return x.CommandContentViolation
	}
	return CommandFailureCause_UNKNOWN_CONTENT_VIOLATION
}

func (m *CommandFailureCause) GetTargetViolation() CommandFailureCause_TargetViolation {
	if x, ok := m.GetType().(*CommandFailureCause_TargetViolation_); ok {
		return x.TargetViolation
	}
	return CommandFailureCause_UNKNOWN_TARGET_VIOLATION
}

func (m *CommandFailureCause) GetComponentError() CommandFailureCause_ComponentError {
	if x, ok := m.GetType().(*CommandFailureCause_ComponentError_); ok {
		return x.ComponentError
	}
	return CommandFailureCause_UNKNOWN_COMPONENT_ERROR
}

func (m *CommandFailureCause) GetCommunicationError() CommandFailureCause_CommunicationError {
	if x, ok := m.GetType().(*CommandFailureCause_CommunicationError_); ok {
		return x.CommunicationError
	}
	return CommandFailureCause_UNKNOWN_COMMUNICATION_ERROR
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*CommandFailureCause) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*CommandFailureCause_CommandContentViolation_)(nil),
		(*CommandFailureCause_TargetViolation_)(nil),
		(*CommandFailureCause_ComponentError_)(nil),
		(*CommandFailureCause_CommunicationError_)(nil),
	}
}

func init() {
	proto.RegisterEnum("autonomic.ext.command.errors.CommandExecutionFailure_ComponentSystem", CommandExecutionFailure_ComponentSystem_name, CommandExecutionFailure_ComponentSystem_value)
	proto.RegisterEnum("autonomic.ext.command.errors.CommandFailureCause_CommandContentViolation", CommandFailureCause_CommandContentViolation_name, CommandFailureCause_CommandContentViolation_value)
	proto.RegisterEnum("autonomic.ext.command.errors.CommandFailureCause_TargetViolation", CommandFailureCause_TargetViolation_name, CommandFailureCause_TargetViolation_value)
	proto.RegisterEnum("autonomic.ext.command.errors.CommandFailureCause_ComponentError", CommandFailureCause_ComponentError_name, CommandFailureCause_ComponentError_value)
	proto.RegisterEnum("autonomic.ext.command.errors.CommandFailureCause_CommunicationError", CommandFailureCause_CommunicationError_name, CommandFailureCause_CommunicationError_value)
	proto.RegisterType((*CommandExecutionFailure)(nil), "autonomic.ext.command.errors.CommandExecutionFailure")
	proto.RegisterType((*PostCommandExecutionComponentStateChanges)(nil), "autonomic.ext.command.errors.PostCommandExecutionComponentStateChanges")
	proto.RegisterType((*CommandFailureCause)(nil), "autonomic.ext.command.errors.CommandFailureCause")
}

func init() {
	proto.RegisterFile("autonomic/ext/command/errors/command_execution.proto", fileDescriptor_597ef42e6d76d889)
}

var fileDescriptor_597ef42e6d76d889 = []byte{
	// 810 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x55, 0xc1, 0x6e, 0xdb, 0x46,
	0x10, 0xd5, 0x4a, 0x72, 0xda, 0x4c, 0x0c, 0x89, 0x59, 0xc1, 0x90, 0x92, 0xb8, 0xad, 0x40, 0xf4,
	0xa0, 0xb6, 0x88, 0x84, 0xb8, 0xfd, 0x80, 0xd2, 0x34, 0x6d, 0x11, 0x15, 0x77, 0x8d, 0x15, 0xed,
	0x22, 0xbd, 0x10, 0xcc, 0x7a, 0x6b, 0x13, 0x35, 0xb9, 0x06, 0xb9, 0x4a, 0x9c, 0x53, 0x8f, 0x41,
	0x81, 0x7e, 0x43, 0x0f, 0xfd, 0x88, 0x7e, 0x47, 0x3f, 0xa7, 0xc7, 0x82, 0x4b, 0x51, 0x26, 0x25,
	0x47, 0x48, 0x72, 0xe4, 0xdb, 0x99, 0xf7, 0x66, 0xde, 0xce, 0x70, 0xe1, 0x87, 0x70, 0xa1, 0x64,
	0x22, 0xe3, 0x88, 0x4f, 0xc4, 0xad, 0x9a, 0x70, 0x19, 0xc7, 0x61, 0x72, 0x31, 0x11, 0x69, 0x2a,
	0xd3, 0xac, 0xfc, 0x0c, 0xc4, 0xad, 0xe0, 0x0b, 0x15, 0xc9, 0x64, 0x7c, 0x93, 0x4a, 0x25, 0xf1,
	0xfe, 0x2a, 0x6b, 0x2c, 0x6e, 0xd5, 0x78, 0x19, 0x36, 0x2e, 0xb2, 0x9e, 0xbe, 0xd8, 0xca, 0x79,
	0x15, 0xa6, 0x17, 0x6f, 0xc2, 0x54, 0x04, 0x99, 0x0a, 0x95, 0x28, 0x08, 0xcd, 0x7f, 0xda, 0xd0,
	0xb7, 0x8b, 0x38, 0xa7, 0xd4, 0x3a, 0x0e, 0xa3, 0xeb, 0x45, 0x2a, 0xf0, 0x0d, 0x18, 0x5c, 0xc6,
	0x37, 0x32, 0x11, 0x89, 0x0a, 0xb2, 0xb7, 0x99, 0x12, 0xf1, 0x00, 0x0d, 0xd1, 0xa8, 0x73, 0xe0,
	0x8c, 0xb7, 0xd5, 0x31, 0x7e, 0x0f, 0x61, 0x8e, 0x17, 0x6c, 0x73, 0x4d, 0xc6, 0xba, 0xbc, 0x0e,
	0xe0, 0xaf, 0xa1, 0x23, 0x45, 0x1c, 0x68, 0x9a, 0x80, 0xcb, 0x0b, 0x31, 0x68, 0x0e, 0xd1, 0x68,
	0x87, 0xed, 0x4a, 0x11, 0x3b, 0x39, 0x68, 0xcb, 0x0b, 0x81, 0xbf, 0x85, 0xc7, 0xd5, 0xa8, 0x44,
	0x89, 0x5b, 0x35, 0x68, 0x0d, 0xd1, 0xe8, 0x21, 0xeb, 0xde, 0x05, 0x6a, 0x18, 0xff, 0x0e, 0xfd,
	0x4a, 0x0f, 0x79, 0xe3, 0x01, 0xbf, 0x0a, 0x93, 0x4b, 0x91, 0x0d, 0xda, 0x43, 0x34, 0x7a, 0x74,
	0x70, 0xb2, 0xbd, 0x95, 0x53, 0x99, 0xa9, 0xf5, 0x76, 0xee, 0xda, 0xc8, 0xf9, 0xec, 0x82, 0x8e,
	0xed, 0xf1, 0xfb, 0x60, 0x2c, 0x60, 0xaf, 0xbc, 0xcc, 0x5f, 0x0b, 0x1b, 0x02, 0x1e, 0x2e, 0x32,
	0x31, 0xd8, 0x19, 0xb6, 0x46, 0x8f, 0x0e, 0x5e, 0x7c, 0x90, 0x93, 0x4b, 0x03, 0xed, 0x3c, 0x91,
	0xf5, 0xf8, 0x26, 0x68, 0x4a, 0xe8, 0xae, 0xb9, 0x8b, 0xf7, 0x61, 0x70, 0x46, 0x7e, 0x22, 0xf4,
	0x67, 0x12, 0xd8, 0xd4, 0x3b, 0xa5, 0xc4, 0x21, 0x7e, 0x30, 0x7f, 0x39, 0xf7, 0x1d, 0xcf, 0x68,
	0x60, 0x0c, 0x1d, 0x9b, 0xd2, 0x99, 0x4b, 0x4e, 0x4a, 0x0c, 0xe1, 0x87, 0xb0, 0xe3, 0x51, 0x9f,
	0x32, 0xa3, 0x89, 0x3f, 0x87, 0xf6, 0x11, 0xa5, 0xcc, 0x68, 0xe1, 0x3d, 0x78, 0x6c, 0x11, 0xdf,
	0x0d, 0xfc, 0xa9, 0x73, 0xbc, 0xca, 0x6f, 0x9b, 0x7f, 0x22, 0xf8, 0xe6, 0x83, 0xcd, 0xc1, 0x01,
	0xec, 0xd5, 0xc7, 0x6f, 0x79, 0x0b, 0x03, 0xa4, 0x5d, 0xf8, 0x6e, 0xbb, 0x0b, 0xd3, 0x65, 0xaa,
	0xa6, 0x64, 0xbd, 0xab, 0xea, 0x67, 0xa1, 0x60, 0xfe, 0xfb, 0x19, 0xf4, 0xee, 0x31, 0x0b, 0xbf,
	0x43, 0xf0, 0xa4, 0xf4, 0x5f, 0x8f, 0x4a, 0xa2, 0x82, 0xd7, 0x91, 0xbc, 0x0e, 0xf3, 0x5a, 0x97,
	0xd3, 0xec, 0x7e, 0xf4, 0x1d, 0x94, 0x98, 0x5d, 0x30, 0x9e, 0x97, 0x84, 0xd3, 0x06, 0xeb, 0xf3,
	0xfb, 0x8f, 0x70, 0x02, 0x86, 0x0a, 0xd3, 0x4b, 0x51, 0xd5, 0x6f, 0x6a, 0x7d, 0xeb, 0xe3, 0xf5,
	0x7d, 0xcd, 0x54, 0xd5, 0xed, 0xaa, 0x3a, 0x84, 0x7f, 0x83, 0xbb, 0xf5, 0x2a, 0x76, 0x45, 0xef,
	0x48, 0xe7, 0xe0, 0xc7, 0x4f, 0x6a, 0xb7, 0x20, 0xd2, 0xbb, 0x35, 0x6d, 0xb0, 0x0e, 0xaf, 0x21,
	0xf8, 0x0d, 0xe8, 0xa9, 0x5c, 0x24, 0x11, 0xd7, 0xea, 0x4b, 0xc1, 0xb6, 0x16, 0x3c, 0xfa, 0x34,
	0x7f, 0x57, 0x64, 0xa5, 0x28, 0xe6, 0x1b, 0xa8, 0xf9, 0x0e, 0xad, 0xfe, 0x5f, 0x1b, 0x8e, 0x7f,
	0x01, 0x4f, 0xee, 0x16, 0x80, 0xf8, 0xf9, 0xf8, 0x9f, 0xbb, 0x74, 0x66, 0xf9, 0x2e, 0x25, 0x46,
	0x03, 0xf7, 0xa0, 0x5b, 0xd9, 0x0f, 0xcf, 0x22, 0x47, 0x06, 0xc2, 0xcf, 0xa0, 0xef, 0xce, 0x66,
	0xce, 0x89, 0x35, 0x2b, 0xc1, 0x32, 0xd7, 0x68, 0xea, 0x43, 0x72, 0x6e, 0xcd, 0xdc, 0xa3, 0x8d,
	0xc3, 0x96, 0x69, 0x43, 0x77, 0xed, 0x56, 0xaa, 0x1b, 0xe8, 0x5b, 0xec, 0xc4, 0xa9, 0xeb, 0x63,
	0xe8, 0x94, 0x6c, 0xc5, 0xa9, 0x81, 0xcc, 0xd7, 0xd0, 0xa9, 0x7b, 0x9d, 0x6b, 0x6e, 0x6e, 0xb1,
	0xc3, 0x18, 0x65, 0x46, 0x23, 0x17, 0x70, 0x89, 0xef, 0x30, 0x52, 0x94, 0x5b, 0x3b, 0x45, 0xd8,
	0x80, 0x5d, 0xcf, 0xf1, 0x28, 0x7b, 0xb9, 0x44, 0x9a, 0xb8, 0x0f, 0x3d, 0x7a, 0xe6, 0x07, 0xf4,
	0x38, 0xa8, 0x1d, 0xb4, 0xcc, 0x3f, 0x10, 0xe0, 0x4d, 0xcf, 0xf1, 0x57, 0xf0, 0xac, 0x6a, 0xd1,
	0x19, 0x71, 0x6d, 0x5d, 0xfd, 0xaa, 0x00, 0x13, 0xbe, 0xb4, 0x29, 0x21, 0x8e, 0x5d, 0xa0, 0x73,
	0xdf, 0x3a, 0x9c, 0xb9, 0xf3, 0xa9, 0x57, 0x2d, 0x63, 0x1f, 0x06, 0x95, 0x18, 0xdf, 0xf5, 0x9c,
	0xbc, 0x86, 0xb2, 0x24, 0x03, 0x76, 0xe7, 0x0e, 0x3b, 0x77, 0x58, 0x59, 0xcb, 0xe1, 0x03, 0x68,
	0xab, 0xb7, 0x37, 0xe2, 0xf0, 0x2f, 0x04, 0x43, 0x2e, 0xe3, 0xad, 0xc3, 0x73, 0xf8, 0x74, 0xfd,
	0xff, 0xa3, 0x0b, 0x3f, 0xcd, 0xdf, 0xb6, 0x53, 0xf4, 0xcb, 0xfc, 0x32, 0x52, 0x57, 0x8b, 0x57,
	0x79, 0xd2, 0x64, 0x45, 0xf3, 0x3c, 0x8c, 0xf2, 0xe7, 0x51, 0xa4, 0x49, 0x78, 0xfd, 0x5c, 0xbf,
	0x82, 0xd9, 0x24, 0x4b, 0xf9, 0x24, 0x0e, 0xa3, 0x64, 0xa2, 0xbf, 0x27, 0xdb, 0xde, 0xd1, 0xff,
	0x10, 0xfa, 0xbb, 0xd9, 0xb2, 0xce, 0xfc, 0x57, 0x0f, 0x74, 0xf0, 0xf7, 0xff, 0x07, 0x00, 0x00,
	0xff, 0xff, 0x38, 0x87, 0x73, 0x09, 0xcb, 0x07, 0x00, 0x00,
}
