/*-
 * ‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾
 * Autonomic Proprietary 1.0
 * ——————————————————————————————————————————————————————————————————————————————
 * Copyright (C) 2020 Autonomic, LLC - All rights reserved
 * ——————————————————————————————————————————————————————————————————————————————
 * Proprietary and confidential.
 *
 * NOTICE:  All information contained herein is, and remains the property of
 * Autonomic, LLC and its suppliers, if any.  The intellectual and technical
 * concepts contained herein are proprietary to Autonomic, LLC and its suppliers
 * and may be covered by U.S. and Foreign Patents, patents in process, and are
 * protected by trade secret or copyright law. Dissemination of this information
 * or reproduction of this material is strictly forbidden unless prior written
 * permission is obtained from Autonomic, LLC.
 *
 * Unauthorized copy of this file, via any medium is strictly prohibited.
 * ______________________________________________________________________________
 */
// Code generated by protoc-gen-go. DO NOT EDIT.
// source: autonomic/ext/command/configuration/configuration.proto

package configuration

import (
	fmt "fmt"
	thirdparty "xk6-fabric/proto/autonomic/ext/command/configuration/thirdparty"
	common "xk6-fabric/proto/autonomic/ext/common"
	telemetry "xk6-fabric/proto/autonomic/ext/telemetry"
	enumerations "xk6-fabric/proto/autonomic/ext/telemetry/enumerations"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ConfigurationResetRequest_ResetScope int32

const (
	ConfigurationResetRequest_UNKNOWN_RESET_TYPE ConfigurationResetRequest_ResetScope = 0
	// Reset selected module parameters to factory settings. Specified module parameters
	// or components, will be passed through the `oem_params` field in the parent ComamndTrigger.
	ConfigurationResetRequest_SELECTIVE_RESET ConfigurationResetRequest_ResetScope = 1
	// Reset all settings to factory settings
	ConfigurationResetRequest_FACTORY_RESET ConfigurationResetRequest_ResetScope = 2
)

var ConfigurationResetRequest_ResetScope_name = map[int32]string{
	0: "UNKNOWN_RESET_TYPE",
	1: "SELECTIVE_RESET",
	2: "FACTORY_RESET",
}

var ConfigurationResetRequest_ResetScope_value = map[string]int32{
	"UNKNOWN_RESET_TYPE": 0,
	"SELECTIVE_RESET":    1,
	"FACTORY_RESET":      2,
}

func (x ConfigurationResetRequest_ResetScope) String() string {
	return proto.EnumName(ConfigurationResetRequest_ResetScope_name, int32(x))
}

func (ConfigurationResetRequest_ResetScope) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1041ffffe6108403, []int{0, 0}
}

type EnvironmentSettings_ConditioningSystem int32

const (
	EnvironmentSettings_UNKNOWN_SYSTEM EnvironmentSettings_ConditioningSystem = 0
	EnvironmentSettings_HEATING        EnvironmentSettings_ConditioningSystem = 1
	EnvironmentSettings_COOLING        EnvironmentSettings_ConditioningSystem = 2
)

var EnvironmentSettings_ConditioningSystem_name = map[int32]string{
	0: "UNKNOWN_SYSTEM",
	1: "HEATING",
	2: "COOLING",
}

var EnvironmentSettings_ConditioningSystem_value = map[string]int32{
	"UNKNOWN_SYSTEM": 0,
	"HEATING":        1,
	"COOLING":        2,
}

func (x EnvironmentSettings_ConditioningSystem) String() string {
	return proto.EnumName(EnvironmentSettings_ConditioningSystem_name, int32(x))
}

func (EnvironmentSettings_ConditioningSystem) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1041ffffe6108403, []int{3, 0}
}

type EnvironmentSettings_ConditioningSystemState int32

const (
	EnvironmentSettings_UNKNOWN_SYSTEM_STATE EnvironmentSettings_ConditioningSystemState = 0
	EnvironmentSettings_ENABLE               EnvironmentSettings_ConditioningSystemState = 1
	EnvironmentSettings_DISABLE              EnvironmentSettings_ConditioningSystemState = 2
)

var EnvironmentSettings_ConditioningSystemState_name = map[int32]string{
	0: "UNKNOWN_SYSTEM_STATE",
	1: "ENABLE",
	2: "DISABLE",
}

var EnvironmentSettings_ConditioningSystemState_value = map[string]int32{
	"UNKNOWN_SYSTEM_STATE": 0,
	"ENABLE":               1,
	"DISABLE":              2,
}

func (x EnvironmentSettings_ConditioningSystemState) String() string {
	return proto.EnumName(EnvironmentSettings_ConditioningSystemState_name, int32(x))
}

func (EnvironmentSettings_ConditioningSystemState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1041ffffe6108403, []int{3, 1}
}

type AuthorizationSettings_AuthorizationMode int32

const (
	AuthorizationSettings_UNKNOWN      AuthorizationSettings_AuthorizationMode = 0
	AuthorizationSettings_UNAUTHORIZED AuthorizationSettings_AuthorizationMode = 1
	AuthorizationSettings_AUTHORIZED   AuthorizationSettings_AuthorizationMode = 2
)

var AuthorizationSettings_AuthorizationMode_name = map[int32]string{
	0: "UNKNOWN",
	1: "UNAUTHORIZED",
	2: "AUTHORIZED",
}

var AuthorizationSettings_AuthorizationMode_value = map[string]int32{
	"UNKNOWN":      0,
	"UNAUTHORIZED": 1,
	"AUTHORIZED":   2,
}

func (x AuthorizationSettings_AuthorizationMode) String() string {
	return proto.EnumName(AuthorizationSettings_AuthorizationMode_name, int32(x))
}

func (AuthorizationSettings_AuthorizationMode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1041ffffe6108403, []int{5, 0}
}

type ModuleUpdateConfiguration_UpdateMode int32

const (
	ModuleUpdateConfiguration_UNSPECIFIED ModuleUpdateConfiguration_UpdateMode = 0
	ModuleUpdateConfiguration_IMMEDIATE   ModuleUpdateConfiguration_UpdateMode = 1
	ModuleUpdateConfiguration_DELAYED     ModuleUpdateConfiguration_UpdateMode = 2
)

var ModuleUpdateConfiguration_UpdateMode_name = map[int32]string{
	0: "UNSPECIFIED",
	1: "IMMEDIATE",
	2: "DELAYED",
}

var ModuleUpdateConfiguration_UpdateMode_value = map[string]int32{
	"UNSPECIFIED": 0,
	"IMMEDIATE":   1,
	"DELAYED":     2,
}

func (x ModuleUpdateConfiguration_UpdateMode) String() string {
	return proto.EnumName(ModuleUpdateConfiguration_UpdateMode_name, int32(x))
}

func (ModuleUpdateConfiguration_UpdateMode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1041ffffe6108403, []int{10, 0}
}

type ModuleUpdateConfiguration_IgnitionMode int32

const (
	ModuleUpdateConfiguration_UNKNOWN                  ModuleUpdateConfiguration_IgnitionMode = 0
	ModuleUpdateConfiguration_ALLOW_WHILE_IGNITION_OFF ModuleUpdateConfiguration_IgnitionMode = 1
	ModuleUpdateConfiguration_REQUIRE_IGNITION_ON      ModuleUpdateConfiguration_IgnitionMode = 2
)

var ModuleUpdateConfiguration_IgnitionMode_name = map[int32]string{
	0: "UNKNOWN",
	1: "ALLOW_WHILE_IGNITION_OFF",
	2: "REQUIRE_IGNITION_ON",
}

var ModuleUpdateConfiguration_IgnitionMode_value = map[string]int32{
	"UNKNOWN":                  0,
	"ALLOW_WHILE_IGNITION_OFF": 1,
	"REQUIRE_IGNITION_ON":      2,
}

func (x ModuleUpdateConfiguration_IgnitionMode) String() string {
	return proto.EnumName(ModuleUpdateConfiguration_IgnitionMode_name, int32(x))
}

func (ModuleUpdateConfiguration_IgnitionMode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1041ffffe6108403, []int{10, 1}
}

type MultiModuleBinaryUpdate_UpdateMode int32

const (
	MultiModuleBinaryUpdate_UNSPECIFIED MultiModuleBinaryUpdate_UpdateMode = 0
	MultiModuleBinaryUpdate_IMMEDIATE   MultiModuleBinaryUpdate_UpdateMode = 1
	MultiModuleBinaryUpdate_DELAYED     MultiModuleBinaryUpdate_UpdateMode = 2
)

var MultiModuleBinaryUpdate_UpdateMode_name = map[int32]string{
	0: "UNSPECIFIED",
	1: "IMMEDIATE",
	2: "DELAYED",
}

var MultiModuleBinaryUpdate_UpdateMode_value = map[string]int32{
	"UNSPECIFIED": 0,
	"IMMEDIATE":   1,
	"DELAYED":     2,
}

func (x MultiModuleBinaryUpdate_UpdateMode) String() string {
	return proto.EnumName(MultiModuleBinaryUpdate_UpdateMode_name, int32(x))
}

func (MultiModuleBinaryUpdate_UpdateMode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1041ffffe6108403, []int{11, 0}
}

type GeoFenceOnDeviceSettings_RequestType int32

const (
	GeoFenceOnDeviceSettings_UNKNOWN GeoFenceOnDeviceSettings_RequestType = 0
	GeoFenceOnDeviceSettings_ADD     GeoFenceOnDeviceSettings_RequestType = 1
	GeoFenceOnDeviceSettings_UPDATE  GeoFenceOnDeviceSettings_RequestType = 2
	GeoFenceOnDeviceSettings_DELETE  GeoFenceOnDeviceSettings_RequestType = 3
	GeoFenceOnDeviceSettings_GET     GeoFenceOnDeviceSettings_RequestType = 5
	GeoFenceOnDeviceSettings_GET_IDS GeoFenceOnDeviceSettings_RequestType = 6
)

var GeoFenceOnDeviceSettings_RequestType_name = map[int32]string{
	0: "UNKNOWN",
	1: "ADD",
	2: "UPDATE",
	3: "DELETE",
	5: "GET",
	6: "GET_IDS",
}

var GeoFenceOnDeviceSettings_RequestType_value = map[string]int32{
	"UNKNOWN": 0,
	"ADD":     1,
	"UPDATE":  2,
	"DELETE":  3,
	"GET":     5,
	"GET_IDS": 6,
}

func (x GeoFenceOnDeviceSettings_RequestType) String() string {
	return proto.EnumName(GeoFenceOnDeviceSettings_RequestType_name, int32(x))
}

func (GeoFenceOnDeviceSettings_RequestType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1041ffffe6108403, []int{15, 0}
}

// A request to reset module settings
type ConfigurationResetRequest struct {
	// whether this is a single module or multi-module reset
	//
	// Types that are valid to be assigned to ModuleScope:
	//	*ConfigurationResetRequest_ModuleName
	//	*ConfigurationResetRequest_AllModules
	ModuleScope          isConfigurationResetRequest_ModuleScope `protobuf_oneof:"module_scope"`
	ResetScope           ConfigurationResetRequest_ResetScope    `protobuf:"varint,3,opt,name=reset_scope,json=resetScope,proto3,enum=autonomic.ext.command.configuration.ConfigurationResetRequest_ResetScope" json:"reset_scope,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                `json:"-"`
	XXX_unrecognized     []byte                                  `json:"-"`
	XXX_sizecache        int32                                   `json:"-"`
}

func (m *ConfigurationResetRequest) Reset()         { *m = ConfigurationResetRequest{} }
func (m *ConfigurationResetRequest) String() string { return proto.CompactTextString(m) }
func (*ConfigurationResetRequest) ProtoMessage()    {}
func (*ConfigurationResetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1041ffffe6108403, []int{0}
}

func (m *ConfigurationResetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigurationResetRequest.Unmarshal(m, b)
}
func (m *ConfigurationResetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigurationResetRequest.Marshal(b, m, deterministic)
}
func (m *ConfigurationResetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigurationResetRequest.Merge(m, src)
}
func (m *ConfigurationResetRequest) XXX_Size() int {
	return xxx_messageInfo_ConfigurationResetRequest.Size(m)
}
func (m *ConfigurationResetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigurationResetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigurationResetRequest proto.InternalMessageInfo

type isConfigurationResetRequest_ModuleScope interface {
	isConfigurationResetRequest_ModuleScope()
}

type ConfigurationResetRequest_ModuleName struct {
	ModuleName string `protobuf:"bytes,1,opt,name=module_name,json=moduleName,proto3,oneof"`
}

type ConfigurationResetRequest_AllModules struct {
	AllModules bool `protobuf:"varint,2,opt,name=all_modules,json=allModules,proto3,oneof"`
}

func (*ConfigurationResetRequest_ModuleName) isConfigurationResetRequest_ModuleScope() {}

func (*ConfigurationResetRequest_AllModules) isConfigurationResetRequest_ModuleScope() {}

func (m *ConfigurationResetRequest) GetModuleScope() isConfigurationResetRequest_ModuleScope {
	if m != nil {
		return m.ModuleScope
	}
	return nil
}

func (m *ConfigurationResetRequest) GetModuleName() string {
	if x, ok := m.GetModuleScope().(*ConfigurationResetRequest_ModuleName); ok {
		return x.ModuleName
	}
	return ""
}

func (m *ConfigurationResetRequest) GetAllModules() bool {
	if x, ok := m.GetModuleScope().(*ConfigurationResetRequest_AllModules); ok {
		return x.AllModules
	}
	return false
}

func (m *ConfigurationResetRequest) GetResetScope() ConfigurationResetRequest_ResetScope {
	if m != nil {
		return m.ResetScope
	}
	return ConfigurationResetRequest_UNKNOWN_RESET_TYPE
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ConfigurationResetRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ConfigurationResetRequest_ModuleName)(nil),
		(*ConfigurationResetRequest_AllModules)(nil),
	}
}

type ConnectivitySettings struct {
	Endpoint             string   `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConnectivitySettings) Reset()         { *m = ConnectivitySettings{} }
func (m *ConnectivitySettings) String() string { return proto.CompactTextString(m) }
func (*ConnectivitySettings) ProtoMessage()    {}
func (*ConnectivitySettings) Descriptor() ([]byte, []int) {
	return fileDescriptor_1041ffffe6108403, []int{1}
}

func (m *ConnectivitySettings) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectivitySettings.Unmarshal(m, b)
}
func (m *ConnectivitySettings) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectivitySettings.Marshal(b, m, deterministic)
}
func (m *ConnectivitySettings) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectivitySettings.Merge(m, src)
}
func (m *ConnectivitySettings) XXX_Size() int {
	return xxx_messageInfo_ConnectivitySettings.Size(m)
}
func (m *ConnectivitySettings) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectivitySettings.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectivitySettings proto.InternalMessageInfo

func (m *ConnectivitySettings) GetEndpoint() string {
	if m != nil {
		return m.Endpoint
	}
	return ""
}

type TelemetrySettings struct {
	// is this device configured to emit vehicle telemetry
	EnableTelemetry      bool     `protobuf:"varint,1,opt,name=enable_telemetry,json=enableTelemetry,proto3" json:"enable_telemetry,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TelemetrySettings) Reset()         { *m = TelemetrySettings{} }
func (m *TelemetrySettings) String() string { return proto.CompactTextString(m) }
func (*TelemetrySettings) ProtoMessage()    {}
func (*TelemetrySettings) Descriptor() ([]byte, []int) {
	return fileDescriptor_1041ffffe6108403, []int{2}
}

func (m *TelemetrySettings) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TelemetrySettings.Unmarshal(m, b)
}
func (m *TelemetrySettings) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TelemetrySettings.Marshal(b, m, deterministic)
}
func (m *TelemetrySettings) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TelemetrySettings.Merge(m, src)
}
func (m *TelemetrySettings) XXX_Size() int {
	return xxx_messageInfo_TelemetrySettings.Size(m)
}
func (m *TelemetrySettings) XXX_DiscardUnknown() {
	xxx_messageInfo_TelemetrySettings.DiscardUnknown(m)
}

var xxx_messageInfo_TelemetrySettings proto.InternalMessageInfo

func (m *TelemetrySettings) GetEnableTelemetry() bool {
	if m != nil {
		return m.EnableTelemetry
	}
	return false
}

// Change environmental controls
type EnvironmentSettings struct {
	// Specify which system to modify
	ConditioningSystem EnvironmentSettings_ConditioningSystem `protobuf:"varint,1,opt,name=conditioning_system,json=conditioningSystem,proto3,enum=autonomic.ext.command.configuration.EnvironmentSettings_ConditioningSystem" json:"conditioning_system,omitempty"`
	// the state the system should be in
	ConditioningSystemState EnvironmentSettings_ConditioningSystemState `protobuf:"varint,2,opt,name=conditioning_system_state,json=conditioningSystemState,proto3,enum=autonomic.ext.command.configuration.EnvironmentSettings_ConditioningSystemState" json:"conditioning_system_state,omitempty"`
	XXX_NoUnkeyedLiteral    struct{}                                    `json:"-"`
	XXX_unrecognized        []byte                                      `json:"-"`
	XXX_sizecache           int32                                       `json:"-"`
}

func (m *EnvironmentSettings) Reset()         { *m = EnvironmentSettings{} }
func (m *EnvironmentSettings) String() string { return proto.CompactTextString(m) }
func (*EnvironmentSettings) ProtoMessage()    {}
func (*EnvironmentSettings) Descriptor() ([]byte, []int) {
	return fileDescriptor_1041ffffe6108403, []int{3}
}

func (m *EnvironmentSettings) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnvironmentSettings.Unmarshal(m, b)
}
func (m *EnvironmentSettings) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnvironmentSettings.Marshal(b, m, deterministic)
}
func (m *EnvironmentSettings) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnvironmentSettings.Merge(m, src)
}
func (m *EnvironmentSettings) XXX_Size() int {
	return xxx_messageInfo_EnvironmentSettings.Size(m)
}
func (m *EnvironmentSettings) XXX_DiscardUnknown() {
	xxx_messageInfo_EnvironmentSettings.DiscardUnknown(m)
}

var xxx_messageInfo_EnvironmentSettings proto.InternalMessageInfo

func (m *EnvironmentSettings) GetConditioningSystem() EnvironmentSettings_ConditioningSystem {
	if m != nil {
		return m.ConditioningSystem
	}
	return EnvironmentSettings_UNKNOWN_SYSTEM
}

func (m *EnvironmentSettings) GetConditioningSystemState() EnvironmentSettings_ConditioningSystemState {
	if m != nil {
		return m.ConditioningSystemState
	}
	return EnvironmentSettings_UNKNOWN_SYSTEM_STATE
}

// Change carrier settings
type CarrierSettings struct {
	Apn2                 string   `protobuf:"bytes,1,opt,name=apn2,proto3" json:"apn2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CarrierSettings) Reset()         { *m = CarrierSettings{} }
func (m *CarrierSettings) String() string { return proto.CompactTextString(m) }
func (*CarrierSettings) ProtoMessage()    {}
func (*CarrierSettings) Descriptor() ([]byte, []int) {
	return fileDescriptor_1041ffffe6108403, []int{4}
}

func (m *CarrierSettings) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CarrierSettings.Unmarshal(m, b)
}
func (m *CarrierSettings) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CarrierSettings.Marshal(b, m, deterministic)
}
func (m *CarrierSettings) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CarrierSettings.Merge(m, src)
}
func (m *CarrierSettings) XXX_Size() int {
	return xxx_messageInfo_CarrierSettings.Size(m)
}
func (m *CarrierSettings) XXX_DiscardUnknown() {
	xxx_messageInfo_CarrierSettings.DiscardUnknown(m)
}

var xxx_messageInfo_CarrierSettings proto.InternalMessageInfo

func (m *CarrierSettings) GetApn2() string {
	if m != nil {
		return m.Apn2
	}
	return ""
}

// Authorization settings
type AuthorizationSettings struct {
	AuthorizationMode    AuthorizationSettings_AuthorizationMode `protobuf:"varint,1,opt,name=authorization_mode,json=authorizationMode,proto3,enum=autonomic.ext.command.configuration.AuthorizationSettings_AuthorizationMode" json:"authorization_mode,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                `json:"-"`
	XXX_unrecognized     []byte                                  `json:"-"`
	XXX_sizecache        int32                                   `json:"-"`
}

func (m *AuthorizationSettings) Reset()         { *m = AuthorizationSettings{} }
func (m *AuthorizationSettings) String() string { return proto.CompactTextString(m) }
func (*AuthorizationSettings) ProtoMessage()    {}
func (*AuthorizationSettings) Descriptor() ([]byte, []int) {
	return fileDescriptor_1041ffffe6108403, []int{5}
}

func (m *AuthorizationSettings) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthorizationSettings.Unmarshal(m, b)
}
func (m *AuthorizationSettings) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthorizationSettings.Marshal(b, m, deterministic)
}
func (m *AuthorizationSettings) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthorizationSettings.Merge(m, src)
}
func (m *AuthorizationSettings) XXX_Size() int {
	return xxx_messageInfo_AuthorizationSettings.Size(m)
}
func (m *AuthorizationSettings) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthorizationSettings.DiscardUnknown(m)
}

var xxx_messageInfo_AuthorizationSettings proto.InternalMessageInfo

func (m *AuthorizationSettings) GetAuthorizationMode() AuthorizationSettings_AuthorizationMode {
	if m != nil {
		return m.AuthorizationMode
	}
	return AuthorizationSettings_UNKNOWN
}

// A request to configure the interrogation logic of a connectivity device
// (i.e. how to query the ECUs on the canbus of a vehicle)
type VehicleInterrogationSettings struct {
	// In the future the interrogation settings may take alternative forms, such as a well-defined sub-message in this
	// oneof. For now, we only support specifying the settings as a bytestream resource which the device should download.
	//
	// Types that are valid to be assigned to DeliveryMethod:
	//	*VehicleInterrogationSettings_BytestreamResource
	DeliveryMethod       isVehicleInterrogationSettings_DeliveryMethod `protobuf_oneof:"delivery_method"`
	XXX_NoUnkeyedLiteral struct{}                                      `json:"-"`
	XXX_unrecognized     []byte                                        `json:"-"`
	XXX_sizecache        int32                                         `json:"-"`
}

func (m *VehicleInterrogationSettings) Reset()         { *m = VehicleInterrogationSettings{} }
func (m *VehicleInterrogationSettings) String() string { return proto.CompactTextString(m) }
func (*VehicleInterrogationSettings) ProtoMessage()    {}
func (*VehicleInterrogationSettings) Descriptor() ([]byte, []int) {
	return fileDescriptor_1041ffffe6108403, []int{6}
}

func (m *VehicleInterrogationSettings) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VehicleInterrogationSettings.Unmarshal(m, b)
}
func (m *VehicleInterrogationSettings) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VehicleInterrogationSettings.Marshal(b, m, deterministic)
}
func (m *VehicleInterrogationSettings) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VehicleInterrogationSettings.Merge(m, src)
}
func (m *VehicleInterrogationSettings) XXX_Size() int {
	return xxx_messageInfo_VehicleInterrogationSettings.Size(m)
}
func (m *VehicleInterrogationSettings) XXX_DiscardUnknown() {
	xxx_messageInfo_VehicleInterrogationSettings.DiscardUnknown(m)
}

var xxx_messageInfo_VehicleInterrogationSettings proto.InternalMessageInfo

type isVehicleInterrogationSettings_DeliveryMethod interface {
	isVehicleInterrogationSettings_DeliveryMethod()
}

type VehicleInterrogationSettings_BytestreamResource struct {
	BytestreamResource *common.BytestreamResource `protobuf:"bytes,1,opt,name=bytestream_resource,json=bytestreamResource,proto3,oneof"`
}

func (*VehicleInterrogationSettings_BytestreamResource) isVehicleInterrogationSettings_DeliveryMethod() {
}

func (m *VehicleInterrogationSettings) GetDeliveryMethod() isVehicleInterrogationSettings_DeliveryMethod {
	if m != nil {
		return m.DeliveryMethod
	}
	return nil
}

func (m *VehicleInterrogationSettings) GetBytestreamResource() *common.BytestreamResource {
	if x, ok := m.GetDeliveryMethod().(*VehicleInterrogationSettings_BytestreamResource); ok {
		return x.BytestreamResource
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*VehicleInterrogationSettings) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*VehicleInterrogationSettings_BytestreamResource)(nil),
	}
}

// A request to configure the ota settings of a connectivity device
type OTAConfigurationSettings struct {
	// In the future the ota configuration settings may take alternative forms, such as a well-defined sub-message in this
	// oneof. For now, we only support specifying the settings as a bytestream resource which the device should download.
	//
	// Types that are valid to be assigned to DeliveryMethod:
	//	*OTAConfigurationSettings_BytestreamResource
	DeliveryMethod       isOTAConfigurationSettings_DeliveryMethod `protobuf_oneof:"delivery_method"`
	XXX_NoUnkeyedLiteral struct{}                                  `json:"-"`
	XXX_unrecognized     []byte                                    `json:"-"`
	XXX_sizecache        int32                                     `json:"-"`
}

func (m *OTAConfigurationSettings) Reset()         { *m = OTAConfigurationSettings{} }
func (m *OTAConfigurationSettings) String() string { return proto.CompactTextString(m) }
func (*OTAConfigurationSettings) ProtoMessage()    {}
func (*OTAConfigurationSettings) Descriptor() ([]byte, []int) {
	return fileDescriptor_1041ffffe6108403, []int{7}
}

func (m *OTAConfigurationSettings) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OTAConfigurationSettings.Unmarshal(m, b)
}
func (m *OTAConfigurationSettings) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OTAConfigurationSettings.Marshal(b, m, deterministic)
}
func (m *OTAConfigurationSettings) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OTAConfigurationSettings.Merge(m, src)
}
func (m *OTAConfigurationSettings) XXX_Size() int {
	return xxx_messageInfo_OTAConfigurationSettings.Size(m)
}
func (m *OTAConfigurationSettings) XXX_DiscardUnknown() {
	xxx_messageInfo_OTAConfigurationSettings.DiscardUnknown(m)
}

var xxx_messageInfo_OTAConfigurationSettings proto.InternalMessageInfo

type isOTAConfigurationSettings_DeliveryMethod interface {
	isOTAConfigurationSettings_DeliveryMethod()
}

type OTAConfigurationSettings_BytestreamResource struct {
	BytestreamResource *common.BytestreamResource `protobuf:"bytes,1,opt,name=bytestream_resource,json=bytestreamResource,proto3,oneof"`
}

func (*OTAConfigurationSettings_BytestreamResource) isOTAConfigurationSettings_DeliveryMethod() {}

func (m *OTAConfigurationSettings) GetDeliveryMethod() isOTAConfigurationSettings_DeliveryMethod {
	if m != nil {
		return m.DeliveryMethod
	}
	return nil
}

func (m *OTAConfigurationSettings) GetBytestreamResource() *common.BytestreamResource {
	if x, ok := m.GetDeliveryMethod().(*OTAConfigurationSettings_BytestreamResource); ok {
		return x.BytestreamResource
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*OTAConfigurationSettings) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*OTAConfigurationSettings_BytestreamResource)(nil),
	}
}

// A binary write to apply to a specific memory/DID address
type BinaryUpdateSegment struct {
	TargetMemoryAddress int32  `protobuf:"varint,1,opt,name=target_memory_address,json=targetMemoryAddress,proto3" json:"target_memory_address,omitempty"`
	Payload             []byte `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	// Types that are valid to be assigned to Scope:
	//	*BinaryUpdateSegment_DidConfigurationType
	Scope                isBinaryUpdateSegment_Scope `protobuf_oneof:"scope"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *BinaryUpdateSegment) Reset()         { *m = BinaryUpdateSegment{} }
func (m *BinaryUpdateSegment) String() string { return proto.CompactTextString(m) }
func (*BinaryUpdateSegment) ProtoMessage()    {}
func (*BinaryUpdateSegment) Descriptor() ([]byte, []int) {
	return fileDescriptor_1041ffffe6108403, []int{8}
}

func (m *BinaryUpdateSegment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BinaryUpdateSegment.Unmarshal(m, b)
}
func (m *BinaryUpdateSegment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BinaryUpdateSegment.Marshal(b, m, deterministic)
}
func (m *BinaryUpdateSegment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BinaryUpdateSegment.Merge(m, src)
}
func (m *BinaryUpdateSegment) XXX_Size() int {
	return xxx_messageInfo_BinaryUpdateSegment.Size(m)
}
func (m *BinaryUpdateSegment) XXX_DiscardUnknown() {
	xxx_messageInfo_BinaryUpdateSegment.DiscardUnknown(m)
}

var xxx_messageInfo_BinaryUpdateSegment proto.InternalMessageInfo

func (m *BinaryUpdateSegment) GetTargetMemoryAddress() int32 {
	if m != nil {
		return m.TargetMemoryAddress
	}
	return 0
}

func (m *BinaryUpdateSegment) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

type isBinaryUpdateSegment_Scope interface {
	isBinaryUpdateSegment_Scope()
}

type BinaryUpdateSegment_DidConfigurationType struct {
	DidConfigurationType string `protobuf:"bytes,3,opt,name=did_configuration_type,json=didConfigurationType,proto3,oneof"`
}

func (*BinaryUpdateSegment_DidConfigurationType) isBinaryUpdateSegment_Scope() {}

func (m *BinaryUpdateSegment) GetScope() isBinaryUpdateSegment_Scope {
	if m != nil {
		return m.Scope
	}
	return nil
}

func (m *BinaryUpdateSegment) GetDidConfigurationType() string {
	if x, ok := m.GetScope().(*BinaryUpdateSegment_DidConfigurationType); ok {
		return x.DidConfigurationType
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*BinaryUpdateSegment) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*BinaryUpdateSegment_DidConfigurationType)(nil),
	}
}

// A ModuleBinaryUpdate is a set of binary writes to apply to memory addresses in a CANBus module/ECU
type ModuleBinaryUpdate struct {
	ModuleId             string                 `protobuf:"bytes,1,opt,name=module_id,json=moduleId,proto3" json:"module_id,omitempty"`
	FieldMemoryMap       string                 `protobuf:"bytes,2,opt,name=field_memory_map,json=fieldMemoryMap,proto3" json:"field_memory_map,omitempty"`
	BinaryUpdateSegments []*BinaryUpdateSegment `protobuf:"bytes,3,rep,name=binary_update_segments,json=binaryUpdateSegments,proto3" json:"binary_update_segments,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *ModuleBinaryUpdate) Reset()         { *m = ModuleBinaryUpdate{} }
func (m *ModuleBinaryUpdate) String() string { return proto.CompactTextString(m) }
func (*ModuleBinaryUpdate) ProtoMessage()    {}
func (*ModuleBinaryUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_1041ffffe6108403, []int{9}
}

func (m *ModuleBinaryUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModuleBinaryUpdate.Unmarshal(m, b)
}
func (m *ModuleBinaryUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModuleBinaryUpdate.Marshal(b, m, deterministic)
}
func (m *ModuleBinaryUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModuleBinaryUpdate.Merge(m, src)
}
func (m *ModuleBinaryUpdate) XXX_Size() int {
	return xxx_messageInfo_ModuleBinaryUpdate.Size(m)
}
func (m *ModuleBinaryUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_ModuleBinaryUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_ModuleBinaryUpdate proto.InternalMessageInfo

func (m *ModuleBinaryUpdate) GetModuleId() string {
	if m != nil {
		return m.ModuleId
	}
	return ""
}

func (m *ModuleBinaryUpdate) GetFieldMemoryMap() string {
	if m != nil {
		return m.FieldMemoryMap
	}
	return ""
}

func (m *ModuleBinaryUpdate) GetBinaryUpdateSegments() []*BinaryUpdateSegment {
	if m != nil {
		return m.BinaryUpdateSegments
	}
	return nil
}

// A ModuleUpdateConfiguration is a set of requirements applied to a MultiModuleBinaryUpdate
type ModuleUpdateConfiguration struct {
	UpdateMode ModuleUpdateConfiguration_UpdateMode `protobuf:"varint,1,opt,name=update_mode,json=updateMode,proto3,enum=autonomic.ext.command.configuration.ModuleUpdateConfiguration_UpdateMode" json:"update_mode,omitempty"`
	// IgnitionMode.ALLOW_WHILE_IGNITION_OFF allows vehicle config changes to be applied when ignition is OFF.
	IgnitionMode         ModuleUpdateConfiguration_IgnitionMode `protobuf:"varint,2,opt,name=ignition_mode,json=ignitionMode,proto3,enum=autonomic.ext.command.configuration.ModuleUpdateConfiguration_IgnitionMode" json:"ignition_mode,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                               `json:"-"`
	XXX_unrecognized     []byte                                 `json:"-"`
	XXX_sizecache        int32                                  `json:"-"`
}

func (m *ModuleUpdateConfiguration) Reset()         { *m = ModuleUpdateConfiguration{} }
func (m *ModuleUpdateConfiguration) String() string { return proto.CompactTextString(m) }
func (*ModuleUpdateConfiguration) ProtoMessage()    {}
func (*ModuleUpdateConfiguration) Descriptor() ([]byte, []int) {
	return fileDescriptor_1041ffffe6108403, []int{10}
}

func (m *ModuleUpdateConfiguration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModuleUpdateConfiguration.Unmarshal(m, b)
}
func (m *ModuleUpdateConfiguration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModuleUpdateConfiguration.Marshal(b, m, deterministic)
}
func (m *ModuleUpdateConfiguration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModuleUpdateConfiguration.Merge(m, src)
}
func (m *ModuleUpdateConfiguration) XXX_Size() int {
	return xxx_messageInfo_ModuleUpdateConfiguration.Size(m)
}
func (m *ModuleUpdateConfiguration) XXX_DiscardUnknown() {
	xxx_messageInfo_ModuleUpdateConfiguration.DiscardUnknown(m)
}

var xxx_messageInfo_ModuleUpdateConfiguration proto.InternalMessageInfo

func (m *ModuleUpdateConfiguration) GetUpdateMode() ModuleUpdateConfiguration_UpdateMode {
	if m != nil {
		return m.UpdateMode
	}
	return ModuleUpdateConfiguration_UNSPECIFIED
}

func (m *ModuleUpdateConfiguration) GetIgnitionMode() ModuleUpdateConfiguration_IgnitionMode {
	if m != nil {
		return m.IgnitionMode
	}
	return ModuleUpdateConfiguration_UNKNOWN
}

// A MultiModuleBinaryUpdate is a set of binary updates to apply to one or more CANBus modules/ECUs
type MultiModuleBinaryUpdate struct {
	// Leverage module_update_configuration instead
	UpdateMode                MultiModuleBinaryUpdate_UpdateMode `protobuf:"varint,1,opt,name=update_mode,json=updateMode,proto3,enum=autonomic.ext.command.configuration.MultiModuleBinaryUpdate_UpdateMode" json:"update_mode,omitempty"` // Deprecated: Do not use.
	ModuleBinaryUpdates       []*ModuleBinaryUpdate              `protobuf:"bytes,2,rep,name=module_binary_updates,json=moduleBinaryUpdates,proto3" json:"module_binary_updates,omitempty"`
	ModuleUpdateConfiguration *ModuleUpdateConfiguration         `protobuf:"bytes,3,opt,name=module_update_configuration,json=moduleUpdateConfiguration,proto3" json:"module_update_configuration,omitempty"`
	XXX_NoUnkeyedLiteral      struct{}                           `json:"-"`
	XXX_unrecognized          []byte                             `json:"-"`
	XXX_sizecache             int32                              `json:"-"`
}

func (m *MultiModuleBinaryUpdate) Reset()         { *m = MultiModuleBinaryUpdate{} }
func (m *MultiModuleBinaryUpdate) String() string { return proto.CompactTextString(m) }
func (*MultiModuleBinaryUpdate) ProtoMessage()    {}
func (*MultiModuleBinaryUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_1041ffffe6108403, []int{11}
}

func (m *MultiModuleBinaryUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MultiModuleBinaryUpdate.Unmarshal(m, b)
}
func (m *MultiModuleBinaryUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MultiModuleBinaryUpdate.Marshal(b, m, deterministic)
}
func (m *MultiModuleBinaryUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MultiModuleBinaryUpdate.Merge(m, src)
}
func (m *MultiModuleBinaryUpdate) XXX_Size() int {
	return xxx_messageInfo_MultiModuleBinaryUpdate.Size(m)
}
func (m *MultiModuleBinaryUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_MultiModuleBinaryUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_MultiModuleBinaryUpdate proto.InternalMessageInfo

// Deprecated: Do not use.
func (m *MultiModuleBinaryUpdate) GetUpdateMode() MultiModuleBinaryUpdate_UpdateMode {
	if m != nil {
		return m.UpdateMode
	}
	return MultiModuleBinaryUpdate_UNSPECIFIED
}

func (m *MultiModuleBinaryUpdate) GetModuleBinaryUpdates() []*ModuleBinaryUpdate {
	if m != nil {
		return m.ModuleBinaryUpdates
	}
	return nil
}

func (m *MultiModuleBinaryUpdate) GetModuleUpdateConfiguration() *ModuleUpdateConfiguration {
	if m != nil {
		return m.ModuleUpdateConfiguration
	}
	return nil
}

// A set of properties describing a telemetry collection package
type TelemetryPackage struct {
	TelemetryName        string                            `protobuf:"bytes,1,opt,name=telemetry_name,json=telemetryName,proto3" json:"telemetry_name,omitempty"`
	ActiveInactiveStatus enumerations.ActiveInactiveStatus `protobuf:"varint,2,opt,name=active_inactive_status,json=activeInactiveStatus,proto3,enum=autonomic.ext.telemetry.enumerations.activeInactiveStatus.ActiveInactiveStatus" json:"active_inactive_status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *TelemetryPackage) Reset()         { *m = TelemetryPackage{} }
func (m *TelemetryPackage) String() string { return proto.CompactTextString(m) }
func (*TelemetryPackage) ProtoMessage()    {}
func (*TelemetryPackage) Descriptor() ([]byte, []int) {
	return fileDescriptor_1041ffffe6108403, []int{12}
}

func (m *TelemetryPackage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TelemetryPackage.Unmarshal(m, b)
}
func (m *TelemetryPackage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TelemetryPackage.Marshal(b, m, deterministic)
}
func (m *TelemetryPackage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TelemetryPackage.Merge(m, src)
}
func (m *TelemetryPackage) XXX_Size() int {
	return xxx_messageInfo_TelemetryPackage.Size(m)
}
func (m *TelemetryPackage) XXX_DiscardUnknown() {
	xxx_messageInfo_TelemetryPackage.DiscardUnknown(m)
}

var xxx_messageInfo_TelemetryPackage proto.InternalMessageInfo

func (m *TelemetryPackage) GetTelemetryName() string {
	if m != nil {
		return m.TelemetryName
	}
	return ""
}

func (m *TelemetryPackage) GetActiveInactiveStatus() enumerations.ActiveInactiveStatus {
	if m != nil {
		return m.ActiveInactiveStatus
	}
	return enumerations.ActiveInactiveStatus_UNDEFINED
}

// A request to configure the telemetry collection settings of a connectivity device
type TelemetryCollectionConfigurationSettings struct {
	TelemetryPackage []*TelemetryPackage `protobuf:"bytes,1,rep,name=telemetry_package,json=telemetryPackage,proto3" json:"telemetry_package,omitempty"` // Deprecated: Do not use.
	// Types that are valid to be assigned to Type:
	//	*TelemetryCollectionConfigurationSettings_EnableByZone
	//	*TelemetryCollectionConfigurationSettings_DisableByZone
	//	*TelemetryCollectionConfigurationSettings_ConfigurationDetails_
	Type                 isTelemetryCollectionConfigurationSettings_Type `protobuf_oneof:"type"`
	XXX_NoUnkeyedLiteral struct{}                                        `json:"-"`
	XXX_unrecognized     []byte                                          `json:"-"`
	XXX_sizecache        int32                                           `json:"-"`
}

func (m *TelemetryCollectionConfigurationSettings) Reset() {
	*m = TelemetryCollectionConfigurationSettings{}
}
func (m *TelemetryCollectionConfigurationSettings) String() string { return proto.CompactTextString(m) }
func (*TelemetryCollectionConfigurationSettings) ProtoMessage()    {}
func (*TelemetryCollectionConfigurationSettings) Descriptor() ([]byte, []int) {
	return fileDescriptor_1041ffffe6108403, []int{13}
}

func (m *TelemetryCollectionConfigurationSettings) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TelemetryCollectionConfigurationSettings.Unmarshal(m, b)
}
func (m *TelemetryCollectionConfigurationSettings) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TelemetryCollectionConfigurationSettings.Marshal(b, m, deterministic)
}
func (m *TelemetryCollectionConfigurationSettings) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TelemetryCollectionConfigurationSettings.Merge(m, src)
}
func (m *TelemetryCollectionConfigurationSettings) XXX_Size() int {
	return xxx_messageInfo_TelemetryCollectionConfigurationSettings.Size(m)
}
func (m *TelemetryCollectionConfigurationSettings) XXX_DiscardUnknown() {
	xxx_messageInfo_TelemetryCollectionConfigurationSettings.DiscardUnknown(m)
}

var xxx_messageInfo_TelemetryCollectionConfigurationSettings proto.InternalMessageInfo

// Deprecated: Do not use.
func (m *TelemetryCollectionConfigurationSettings) GetTelemetryPackage() []*TelemetryPackage {
	if m != nil {
		return m.TelemetryPackage
	}
	return nil
}

type isTelemetryCollectionConfigurationSettings_Type interface {
	isTelemetryCollectionConfigurationSettings_Type()
}

type TelemetryCollectionConfigurationSettings_EnableByZone struct {
	EnableByZone *TelemetryCollectionConfigurationSettings_EnableByZoneConfigurationDetails `protobuf:"bytes,2,opt,name=enable_by_zone,json=enableByZone,proto3,oneof"`
}

type TelemetryCollectionConfigurationSettings_DisableByZone struct {
	DisableByZone *TelemetryCollectionConfigurationSettings_DisableByZoneConfigurationDetails `protobuf:"bytes,3,opt,name=disable_by_zone,json=disableByZone,proto3,oneof"`
}

type TelemetryCollectionConfigurationSettings_ConfigurationDetails_ struct {
	ConfigurationDetails *TelemetryCollectionConfigurationSettings_ConfigurationDetails `protobuf:"bytes,4,opt,name=configuration_details,json=configurationDetails,proto3,oneof"`
}

func (*TelemetryCollectionConfigurationSettings_EnableByZone) isTelemetryCollectionConfigurationSettings_Type() {
}

func (*TelemetryCollectionConfigurationSettings_DisableByZone) isTelemetryCollectionConfigurationSettings_Type() {
}

func (*TelemetryCollectionConfigurationSettings_ConfigurationDetails_) isTelemetryCollectionConfigurationSettings_Type() {
}

func (m *TelemetryCollectionConfigurationSettings) GetType() isTelemetryCollectionConfigurationSettings_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *TelemetryCollectionConfigurationSettings) GetEnableByZone() *TelemetryCollectionConfigurationSettings_EnableByZoneConfigurationDetails {
	if x, ok := m.GetType().(*TelemetryCollectionConfigurationSettings_EnableByZone); ok {
		return x.EnableByZone
	}
	return nil
}

func (m *TelemetryCollectionConfigurationSettings) GetDisableByZone() *TelemetryCollectionConfigurationSettings_DisableByZoneConfigurationDetails {
	if x, ok := m.GetType().(*TelemetryCollectionConfigurationSettings_DisableByZone); ok {
		return x.DisableByZone
	}
	return nil
}

func (m *TelemetryCollectionConfigurationSettings) GetConfigurationDetails() *TelemetryCollectionConfigurationSettings_ConfigurationDetails {
	if x, ok := m.GetType().(*TelemetryCollectionConfigurationSettings_ConfigurationDetails_); ok {
		return x.ConfigurationDetails
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*TelemetryCollectionConfigurationSettings) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*TelemetryCollectionConfigurationSettings_EnableByZone)(nil),
		(*TelemetryCollectionConfigurationSettings_DisableByZone)(nil),
		(*TelemetryCollectionConfigurationSettings_ConfigurationDetails_)(nil),
	}
}

type TelemetryCollectionConfigurationSettings_EnableByZoneConfigurationDetails struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TelemetryCollectionConfigurationSettings_EnableByZoneConfigurationDetails) Reset() {
	*m = TelemetryCollectionConfigurationSettings_EnableByZoneConfigurationDetails{}
}
func (m *TelemetryCollectionConfigurationSettings_EnableByZoneConfigurationDetails) String() string {
	return proto.CompactTextString(m)
}
func (*TelemetryCollectionConfigurationSettings_EnableByZoneConfigurationDetails) ProtoMessage() {}
func (*TelemetryCollectionConfigurationSettings_EnableByZoneConfigurationDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_1041ffffe6108403, []int{13, 0}
}

func (m *TelemetryCollectionConfigurationSettings_EnableByZoneConfigurationDetails) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TelemetryCollectionConfigurationSettings_EnableByZoneConfigurationDetails.Unmarshal(m, b)
}
func (m *TelemetryCollectionConfigurationSettings_EnableByZoneConfigurationDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TelemetryCollectionConfigurationSettings_EnableByZoneConfigurationDetails.Marshal(b, m, deterministic)
}
func (m *TelemetryCollectionConfigurationSettings_EnableByZoneConfigurationDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TelemetryCollectionConfigurationSettings_EnableByZoneConfigurationDetails.Merge(m, src)
}
func (m *TelemetryCollectionConfigurationSettings_EnableByZoneConfigurationDetails) XXX_Size() int {
	return xxx_messageInfo_TelemetryCollectionConfigurationSettings_EnableByZoneConfigurationDetails.Size(m)
}
func (m *TelemetryCollectionConfigurationSettings_EnableByZoneConfigurationDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_TelemetryCollectionConfigurationSettings_EnableByZoneConfigurationDetails.DiscardUnknown(m)
}

var xxx_messageInfo_TelemetryCollectionConfigurationSettings_EnableByZoneConfigurationDetails proto.InternalMessageInfo

type TelemetryCollectionConfigurationSettings_DisableByZoneConfigurationDetails struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TelemetryCollectionConfigurationSettings_DisableByZoneConfigurationDetails) Reset() {
	*m = TelemetryCollectionConfigurationSettings_DisableByZoneConfigurationDetails{}
}
func (m *TelemetryCollectionConfigurationSettings_DisableByZoneConfigurationDetails) String() string {
	return proto.CompactTextString(m)
}
func (*TelemetryCollectionConfigurationSettings_DisableByZoneConfigurationDetails) ProtoMessage() {}
func (*TelemetryCollectionConfigurationSettings_DisableByZoneConfigurationDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_1041ffffe6108403, []int{13, 1}
}

func (m *TelemetryCollectionConfigurationSettings_DisableByZoneConfigurationDetails) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TelemetryCollectionConfigurationSettings_DisableByZoneConfigurationDetails.Unmarshal(m, b)
}
func (m *TelemetryCollectionConfigurationSettings_DisableByZoneConfigurationDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TelemetryCollectionConfigurationSettings_DisableByZoneConfigurationDetails.Marshal(b, m, deterministic)
}
func (m *TelemetryCollectionConfigurationSettings_DisableByZoneConfigurationDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TelemetryCollectionConfigurationSettings_DisableByZoneConfigurationDetails.Merge(m, src)
}
func (m *TelemetryCollectionConfigurationSettings_DisableByZoneConfigurationDetails) XXX_Size() int {
	return xxx_messageInfo_TelemetryCollectionConfigurationSettings_DisableByZoneConfigurationDetails.Size(m)
}
func (m *TelemetryCollectionConfigurationSettings_DisableByZoneConfigurationDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_TelemetryCollectionConfigurationSettings_DisableByZoneConfigurationDetails.DiscardUnknown(m)
}

var xxx_messageInfo_TelemetryCollectionConfigurationSettings_DisableByZoneConfigurationDetails proto.InternalMessageInfo

type TelemetryCollectionConfigurationSettings_ConfigurationDetails struct {
	TelemetryPackages    []*TelemetryPackage `protobuf:"bytes,1,rep,name=telemetry_packages,json=telemetryPackages,proto3" json:"telemetry_packages,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *TelemetryCollectionConfigurationSettings_ConfigurationDetails) Reset() {
	*m = TelemetryCollectionConfigurationSettings_ConfigurationDetails{}
}
func (m *TelemetryCollectionConfigurationSettings_ConfigurationDetails) String() string {
	return proto.CompactTextString(m)
}
func (*TelemetryCollectionConfigurationSettings_ConfigurationDetails) ProtoMessage() {}
func (*TelemetryCollectionConfigurationSettings_ConfigurationDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_1041ffffe6108403, []int{13, 2}
}

func (m *TelemetryCollectionConfigurationSettings_ConfigurationDetails) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TelemetryCollectionConfigurationSettings_ConfigurationDetails.Unmarshal(m, b)
}
func (m *TelemetryCollectionConfigurationSettings_ConfigurationDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TelemetryCollectionConfigurationSettings_ConfigurationDetails.Marshal(b, m, deterministic)
}
func (m *TelemetryCollectionConfigurationSettings_ConfigurationDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TelemetryCollectionConfigurationSettings_ConfigurationDetails.Merge(m, src)
}
func (m *TelemetryCollectionConfigurationSettings_ConfigurationDetails) XXX_Size() int {
	return xxx_messageInfo_TelemetryCollectionConfigurationSettings_ConfigurationDetails.Size(m)
}
func (m *TelemetryCollectionConfigurationSettings_ConfigurationDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_TelemetryCollectionConfigurationSettings_ConfigurationDetails.DiscardUnknown(m)
}

var xxx_messageInfo_TelemetryCollectionConfigurationSettings_ConfigurationDetails proto.InternalMessageInfo

func (m *TelemetryCollectionConfigurationSettings_ConfigurationDetails) GetTelemetryPackages() []*TelemetryPackage {
	if m != nil {
		return m.TelemetryPackages
	}
	return nil
}

// Update the configurations on a connectivity device or CANBus Module
type ConfigurationUpdateRequest struct {
	// Settings governing connectivity
	ConnectivitySettings *ConnectivitySettings `protobuf:"bytes,1,opt,name=connectivity_settings,json=connectivitySettings,proto3" json:"connectivity_settings,omitempty"`
	// Settings governing telemetry
	TelemetrySettings *TelemetrySettings `protobuf:"bytes,2,opt,name=telemetry_settings,json=telemetrySettings,proto3" json:"telemetry_settings,omitempty"`
	// Telemetry settings pertaining to reporting requirements imposed by third parties
	ThirdpartyTelemetrySettings *thirdparty.TelemetryConfiguration `protobuf:"bytes,3,opt,name=thirdparty_telemetry_settings,json=thirdpartyTelemetrySettings,proto3" json:"thirdparty_telemetry_settings,omitempty"`
	// Settings governing vehicle environment
	EnvironmentSettings *EnvironmentSettings `protobuf:"bytes,4,opt,name=environment_settings,json=environmentSettings,proto3" json:"environment_settings,omitempty"`
	// Settings governing carrier
	CarrierSettings *CarrierSettings `protobuf:"bytes,5,opt,name=carrier_settings,json=carrierSettings,proto3" json:"carrier_settings,omitempty"`
	// Settings governing authorization
	AuthorizationSettings *AuthorizationSettings `protobuf:"bytes,6,opt,name=authorization_settings,json=authorizationSettings,proto3" json:"authorization_settings,omitempty"`
	// Settings governing how to query the vehicle ECUs
	VehicleInterrogationSettings *VehicleInterrogationSettings `protobuf:"bytes,7,opt,name=vehicle_interrogation_settings,json=vehicleInterrogationSettings,proto3" json:"vehicle_interrogation_settings,omitempty"`
	// Settings governing how to configure the ota software update configuration on a device
	OtaConfigurationSettings *OTAConfigurationSettings `protobuf:"bytes,8,opt,name=ota_configuration_settings,json=otaConfigurationSettings,proto3" json:"ota_configuration_settings,omitempty"`
	// Raw binary configuration updates targeted at memory addresses within modules / ECUs on CANbus
	MultiModuleBinaryUpdate *MultiModuleBinaryUpdate `protobuf:"bytes,9,opt,name=multi_module_binary_update,json=multiModuleBinaryUpdate,proto3" json:"multi_module_binary_update,omitempty"`
	// Settings governing telemetry collection
	TelemetryCollectionConfigurationSettings *TelemetryCollectionConfigurationSettings `protobuf:"bytes,10,opt,name=telemetry_collection_configuration_settings,json=telemetryCollectionConfigurationSettings,proto3" json:"telemetry_collection_configuration_settings,omitempty"`
	// Settings governing geofence on device (the geofence is created on the device and not managed in TMC)
	GeofenceOnDeviceSettings *GeoFenceOnDeviceSettings `protobuf:"bytes,11,opt,name=geofence_on_device_settings,json=geofenceOnDeviceSettings,proto3" json:"geofence_on_device_settings,omitempty"`
	// Configuration settings that are being updated by this request
	Configuration        []*telemetry.Configuration `protobuf:"bytes,100,rep,name=configuration,proto3" json:"configuration,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *ConfigurationUpdateRequest) Reset()         { *m = ConfigurationUpdateRequest{} }
func (m *ConfigurationUpdateRequest) String() string { return proto.CompactTextString(m) }
func (*ConfigurationUpdateRequest) ProtoMessage()    {}
func (*ConfigurationUpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1041ffffe6108403, []int{14}
}

func (m *ConfigurationUpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigurationUpdateRequest.Unmarshal(m, b)
}
func (m *ConfigurationUpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigurationUpdateRequest.Marshal(b, m, deterministic)
}
func (m *ConfigurationUpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigurationUpdateRequest.Merge(m, src)
}
func (m *ConfigurationUpdateRequest) XXX_Size() int {
	return xxx_messageInfo_ConfigurationUpdateRequest.Size(m)
}
func (m *ConfigurationUpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigurationUpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigurationUpdateRequest proto.InternalMessageInfo

func (m *ConfigurationUpdateRequest) GetConnectivitySettings() *ConnectivitySettings {
	if m != nil {
		return m.ConnectivitySettings
	}
	return nil
}

func (m *ConfigurationUpdateRequest) GetTelemetrySettings() *TelemetrySettings {
	if m != nil {
		return m.TelemetrySettings
	}
	return nil
}

func (m *ConfigurationUpdateRequest) GetThirdpartyTelemetrySettings() *thirdparty.TelemetryConfiguration {
	if m != nil {
		return m.ThirdpartyTelemetrySettings
	}
	return nil
}

func (m *ConfigurationUpdateRequest) GetEnvironmentSettings() *EnvironmentSettings {
	if m != nil {
		return m.EnvironmentSettings
	}
	return nil
}

func (m *ConfigurationUpdateRequest) GetCarrierSettings() *CarrierSettings {
	if m != nil {
		return m.CarrierSettings
	}
	return nil
}

func (m *ConfigurationUpdateRequest) GetAuthorizationSettings() *AuthorizationSettings {
	if m != nil {
		return m.AuthorizationSettings
	}
	return nil
}

func (m *ConfigurationUpdateRequest) GetVehicleInterrogationSettings() *VehicleInterrogationSettings {
	if m != nil {
		return m.VehicleInterrogationSettings
	}
	return nil
}

func (m *ConfigurationUpdateRequest) GetOtaConfigurationSettings() *OTAConfigurationSettings {
	if m != nil {
		return m.OtaConfigurationSettings
	}
	return nil
}

func (m *ConfigurationUpdateRequest) GetMultiModuleBinaryUpdate() *MultiModuleBinaryUpdate {
	if m != nil {
		return m.MultiModuleBinaryUpdate
	}
	return nil
}

func (m *ConfigurationUpdateRequest) GetTelemetryCollectionConfigurationSettings() *TelemetryCollectionConfigurationSettings {
	if m != nil {
		return m.TelemetryCollectionConfigurationSettings
	}
	return nil
}

func (m *ConfigurationUpdateRequest) GetGeofenceOnDeviceSettings() *GeoFenceOnDeviceSettings {
	if m != nil {
		return m.GeofenceOnDeviceSettings
	}
	return nil
}

func (m *ConfigurationUpdateRequest) GetConfiguration() []*telemetry.Configuration {
	if m != nil {
		return m.Configuration
	}
	return nil
}

type GeoFenceOnDeviceSettings struct {
	RequestType          GeoFenceOnDeviceSettings_RequestType `protobuf:"varint,1,opt,name=request_type,json=requestType,proto3,enum=autonomic.ext.command.configuration.GeoFenceOnDeviceSettings_RequestType" json:"request_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                             `json:"-"`
	XXX_unrecognized     []byte                               `json:"-"`
	XXX_sizecache        int32                                `json:"-"`
}

func (m *GeoFenceOnDeviceSettings) Reset()         { *m = GeoFenceOnDeviceSettings{} }
func (m *GeoFenceOnDeviceSettings) String() string { return proto.CompactTextString(m) }
func (*GeoFenceOnDeviceSettings) ProtoMessage()    {}
func (*GeoFenceOnDeviceSettings) Descriptor() ([]byte, []int) {
	return fileDescriptor_1041ffffe6108403, []int{15}
}

func (m *GeoFenceOnDeviceSettings) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GeoFenceOnDeviceSettings.Unmarshal(m, b)
}
func (m *GeoFenceOnDeviceSettings) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GeoFenceOnDeviceSettings.Marshal(b, m, deterministic)
}
func (m *GeoFenceOnDeviceSettings) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GeoFenceOnDeviceSettings.Merge(m, src)
}
func (m *GeoFenceOnDeviceSettings) XXX_Size() int {
	return xxx_messageInfo_GeoFenceOnDeviceSettings.Size(m)
}
func (m *GeoFenceOnDeviceSettings) XXX_DiscardUnknown() {
	xxx_messageInfo_GeoFenceOnDeviceSettings.DiscardUnknown(m)
}

var xxx_messageInfo_GeoFenceOnDeviceSettings proto.InternalMessageInfo

func (m *GeoFenceOnDeviceSettings) GetRequestType() GeoFenceOnDeviceSettings_RequestType {
	if m != nil {
		return m.RequestType
	}
	return GeoFenceOnDeviceSettings_UNKNOWN
}

func init() {
	proto.RegisterEnum("autonomic.ext.command.configuration.ConfigurationResetRequest_ResetScope", ConfigurationResetRequest_ResetScope_name, ConfigurationResetRequest_ResetScope_value)
	proto.RegisterEnum("autonomic.ext.command.configuration.EnvironmentSettings_ConditioningSystem", EnvironmentSettings_ConditioningSystem_name, EnvironmentSettings_ConditioningSystem_value)
	proto.RegisterEnum("autonomic.ext.command.configuration.EnvironmentSettings_ConditioningSystemState", EnvironmentSettings_ConditioningSystemState_name, EnvironmentSettings_ConditioningSystemState_value)
	proto.RegisterEnum("autonomic.ext.command.configuration.AuthorizationSettings_AuthorizationMode", AuthorizationSettings_AuthorizationMode_name, AuthorizationSettings_AuthorizationMode_value)
	proto.RegisterEnum("autonomic.ext.command.configuration.ModuleUpdateConfiguration_UpdateMode", ModuleUpdateConfiguration_UpdateMode_name, ModuleUpdateConfiguration_UpdateMode_value)
	proto.RegisterEnum("autonomic.ext.command.configuration.ModuleUpdateConfiguration_IgnitionMode", ModuleUpdateConfiguration_IgnitionMode_name, ModuleUpdateConfiguration_IgnitionMode_value)
	proto.RegisterEnum("autonomic.ext.command.configuration.MultiModuleBinaryUpdate_UpdateMode", MultiModuleBinaryUpdate_UpdateMode_name, MultiModuleBinaryUpdate_UpdateMode_value)
	proto.RegisterEnum("autonomic.ext.command.configuration.GeoFenceOnDeviceSettings_RequestType", GeoFenceOnDeviceSettings_RequestType_name, GeoFenceOnDeviceSettings_RequestType_value)
	proto.RegisterType((*ConfigurationResetRequest)(nil), "autonomic.ext.command.configuration.ConfigurationResetRequest")
	proto.RegisterType((*ConnectivitySettings)(nil), "autonomic.ext.command.configuration.ConnectivitySettings")
	proto.RegisterType((*TelemetrySettings)(nil), "autonomic.ext.command.configuration.TelemetrySettings")
	proto.RegisterType((*EnvironmentSettings)(nil), "autonomic.ext.command.configuration.EnvironmentSettings")
	proto.RegisterType((*CarrierSettings)(nil), "autonomic.ext.command.configuration.CarrierSettings")
	proto.RegisterType((*AuthorizationSettings)(nil), "autonomic.ext.command.configuration.AuthorizationSettings")
	proto.RegisterType((*VehicleInterrogationSettings)(nil), "autonomic.ext.command.configuration.VehicleInterrogationSettings")
	proto.RegisterType((*OTAConfigurationSettings)(nil), "autonomic.ext.command.configuration.OTAConfigurationSettings")
	proto.RegisterType((*BinaryUpdateSegment)(nil), "autonomic.ext.command.configuration.BinaryUpdateSegment")
	proto.RegisterType((*ModuleBinaryUpdate)(nil), "autonomic.ext.command.configuration.ModuleBinaryUpdate")
	proto.RegisterType((*ModuleUpdateConfiguration)(nil), "autonomic.ext.command.configuration.ModuleUpdateConfiguration")
	proto.RegisterType((*MultiModuleBinaryUpdate)(nil), "autonomic.ext.command.configuration.MultiModuleBinaryUpdate")
	proto.RegisterType((*TelemetryPackage)(nil), "autonomic.ext.command.configuration.TelemetryPackage")
	proto.RegisterType((*TelemetryCollectionConfigurationSettings)(nil), "autonomic.ext.command.configuration.TelemetryCollectionConfigurationSettings")
	proto.RegisterType((*TelemetryCollectionConfigurationSettings_EnableByZoneConfigurationDetails)(nil), "autonomic.ext.command.configuration.TelemetryCollectionConfigurationSettings.EnableByZoneConfigurationDetails")
	proto.RegisterType((*TelemetryCollectionConfigurationSettings_DisableByZoneConfigurationDetails)(nil), "autonomic.ext.command.configuration.TelemetryCollectionConfigurationSettings.DisableByZoneConfigurationDetails")
	proto.RegisterType((*TelemetryCollectionConfigurationSettings_ConfigurationDetails)(nil), "autonomic.ext.command.configuration.TelemetryCollectionConfigurationSettings.ConfigurationDetails")
	proto.RegisterType((*ConfigurationUpdateRequest)(nil), "autonomic.ext.command.configuration.ConfigurationUpdateRequest")
	proto.RegisterType((*GeoFenceOnDeviceSettings)(nil), "autonomic.ext.command.configuration.GeoFenceOnDeviceSettings")
}

func init() {
	proto.RegisterFile("autonomic/ext/command/configuration/configuration.proto", fileDescriptor_1041ffffe6108403)
}

var fileDescriptor_1041ffffe6108403 = []byte{
	// 1795 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x58, 0xcd, 0x6f, 0xdb, 0xc8,
	0x15, 0x37, 0xa5, 0xc4, 0x8e, 0x9f, 0x6c, 0x99, 0x1e, 0xf9, 0x43, 0x51, 0xd2, 0xc2, 0xcb, 0x60,
	0x5b, 0x17, 0x8b, 0x95, 0x50, 0xb5, 0xdd, 0x8f, 0xa2, 0x0d, 0x20, 0x59, 0xb4, 0x4d, 0xac, 0x3e,
	0xbc, 0x23, 0x79, 0x83, 0xe4, 0x42, 0x50, 0xe4, 0x44, 0x66, 0x43, 0x72, 0xb4, 0xe4, 0xc8, 0x88,
	0x76, 0x83, 0xde, 0x8a, 0x16, 0x45, 0x6f, 0x05, 0x5a, 0xf4, 0x5a, 0xec, 0xad, 0x05, 0x0a, 0x14,
	0x3d, 0x17, 0xe8, 0xb9, 0xff, 0x40, 0x81, 0xfe, 0x23, 0x3d, 0x16, 0x9c, 0xa1, 0x29, 0xd2, 0xa2,
	0x12, 0x39, 0x31, 0xb0, 0x37, 0xce, 0x9b, 0x37, 0xbf, 0xf7, 0x39, 0x6f, 0xde, 0x23, 0x7c, 0x6c,
	0x4c, 0x18, 0xf5, 0xa8, 0x6b, 0x9b, 0x35, 0xf2, 0x92, 0xd5, 0x4c, 0xea, 0xba, 0x86, 0x67, 0xd5,
	0x4c, 0xea, 0x3d, 0xb7, 0x47, 0x13, 0xdf, 0x60, 0x36, 0xf5, 0xd2, 0xab, 0xea, 0xd8, 0xa7, 0x8c,
	0xa2, 0x47, 0xf1, 0xc1, 0x2a, 0x79, 0xc9, 0xaa, 0xd1, 0xc1, 0x6a, 0x8a, 0xb5, 0xf2, 0x78, 0x19,
	0x74, 0x76, 0x61, 0xfb, 0xd6, 0xd8, 0xf0, 0xd9, 0xb4, 0xc6, 0x88, 0x43, 0x5c, 0xc2, 0xfc, 0xa9,
	0x10, 0x52, 0x79, 0x34, 0x7f, 0x9e, 0x7a, 0x35, 0xe2, 0x59, 0x63, 0x6a, 0x7b, 0x2c, 0x62, 0xfa,
	0x20, 0xcd, 0x14, 0x63, 0x64, 0xa9, 0x5d, 0x69, 0x2c, 0x62, 0x26, 0xde, 0xc4, 0x25, 0x82, 0x35,
	0xa8, 0x19, 0x26, 0xb3, 0x2f, 0x89, 0x6e, 0x7b, 0xd1, 0x47, 0xc0, 0x0c, 0x36, 0x09, 0x04, 0x84,
	0xf2, 0x97, 0x1c, 0xdc, 0x3f, 0x4a, 0x42, 0x63, 0x12, 0x10, 0x86, 0xc9, 0x97, 0x13, 0x12, 0x30,
	0xf4, 0x1e, 0x14, 0x5c, 0x6a, 0x4d, 0x1c, 0xa2, 0x7b, 0x86, 0x4b, 0xca, 0xd2, 0x81, 0x74, 0xb8,
	0x7e, 0xba, 0x82, 0x41, 0x10, 0xbb, 0x86, 0x4b, 0x42, 0x16, 0xc3, 0x71, 0x74, 0x41, 0x09, 0xca,
	0xb9, 0x03, 0xe9, 0xf0, 0x5e, 0xc8, 0x62, 0x38, 0x4e, 0x47, 0xd0, 0xd0, 0x2f, 0xa0, 0xe0, 0x87,
	0xa8, 0x7a, 0x60, 0xd2, 0x31, 0x29, 0xe7, 0x0f, 0xa4, 0xc3, 0x62, 0x5d, 0xab, 0x2e, 0xe1, 0xf3,
	0xea, 0x42, 0xd5, 0xaa, 0x7c, 0xd1, 0x0f, 0x01, 0x31, 0xf8, 0xf1, 0xb7, 0xd2, 0x06, 0x98, 0xed,
	0xa0, 0x3d, 0x40, 0xe7, 0xdd, 0xcf, 0xba, 0xbd, 0x27, 0x5d, 0x1d, 0xab, 0x7d, 0x75, 0xa0, 0x0f,
	0x9e, 0x9e, 0xa9, 0xf2, 0x0a, 0x2a, 0xc1, 0x56, 0x5f, 0x6d, 0xab, 0x47, 0x03, 0xed, 0x0b, 0x55,
	0xec, 0xc8, 0x12, 0xda, 0x86, 0xcd, 0xe3, 0xc6, 0xd1, 0xa0, 0x87, 0x9f, 0x46, 0xa4, 0x5c, 0xb3,
	0x08, 0x1b, 0x91, 0xfd, 0x5c, 0x75, 0xa5, 0x0e, 0x3b, 0x47, 0xd4, 0xf3, 0x48, 0xe8, 0x48, 0x9b,
	0x4d, 0xfb, 0x84, 0x31, 0xdb, 0x1b, 0x05, 0xa8, 0x02, 0xf7, 0xae, 0xe2, 0x28, 0x9c, 0x84, 0xe3,
	0xb5, 0xf2, 0x18, 0xb6, 0x07, 0x57, 0x81, 0x89, 0x0f, 0xfc, 0x00, 0x64, 0xe2, 0x19, 0x43, 0x87,
	0xe8, 0x71, 0xd0, 0xf8, 0xc1, 0x7b, 0x78, 0x4b, 0xd0, 0xe3, 0x23, 0xca, 0x3f, 0xf2, 0x50, 0x52,
	0xbd, 0x4b, 0xdb, 0xa7, 0x9e, 0x4b, 0x3c, 0x16, 0x43, 0xbc, 0x82, 0x92, 0x49, 0x3d, 0xcb, 0x0e,
	0x3d, 0x63, 0x7b, 0x23, 0x3d, 0x98, 0x06, 0x8c, 0xb8, 0x1c, 0xa5, 0x58, 0xff, 0x6c, 0x29, 0xef,
	0x66, 0xc0, 0x86, 0x1e, 0x8f, 0x31, 0xfb, 0x1c, 0x12, 0x23, 0x73, 0x8e, 0x86, 0x7e, 0x27, 0xc1,
	0xfd, 0x0c, 0xf1, 0x3c, 0xb9, 0x08, 0xcf, 0x82, 0x62, 0xfd, 0xec, 0x16, 0x95, 0xe8, 0x87, 0xb8,
	0x78, 0xdf, 0xcc, 0xde, 0x50, 0x9a, 0x80, 0xe6, 0xcf, 0x20, 0x04, 0xc5, 0xab, 0xf0, 0xf7, 0x9f,
	0xf6, 0x07, 0x6a, 0x47, 0x5e, 0x41, 0x05, 0x58, 0x3b, 0x55, 0x1b, 0x03, 0xad, 0x7b, 0x22, 0x4b,
	0xe1, 0xe2, 0xa8, 0xd7, 0x6b, 0x87, 0x8b, 0x9c, 0xd2, 0x86, 0xfd, 0x05, 0x72, 0x51, 0x19, 0x76,
	0xd2, 0x40, 0x7a, 0x7f, 0xd0, 0x18, 0x84, 0x99, 0x04, 0xb0, 0xaa, 0x76, 0x1b, 0xcd, 0xb6, 0x2a,
	0xd0, 0x5a, 0x5a, 0x9f, 0x2f, 0x72, 0xca, 0xfb, 0xb0, 0x75, 0x64, 0xf8, 0xbe, 0x4d, 0xfc, 0x38,
	0x62, 0x08, 0xee, 0x18, 0x63, 0xaf, 0x1e, 0x65, 0x08, 0xff, 0x56, 0xfe, 0x23, 0xc1, 0x6e, 0x63,
	0xc2, 0x2e, 0xa8, 0x6f, 0x7f, 0xc5, 0xfd, 0x11, 0x73, 0x7f, 0x0d, 0xc8, 0x48, 0x6e, 0x84, 0x57,
	0x8c, 0x44, 0xe1, 0x6d, 0x2f, 0xe5, 0xd9, 0x4c, 0xdc, 0x34, 0xb5, 0x43, 0x2d, 0x82, 0xb7, 0x8d,
	0xeb, 0x24, 0xa5, 0x09, 0xdb, 0x73, 0x7c, 0xa1, 0x7d, 0x91, 0x17, 0xe4, 0x15, 0x24, 0xc3, 0xc6,
	0x79, 0xb7, 0x71, 0x3e, 0x38, 0xed, 0x61, 0xed, 0x99, 0xda, 0x92, 0x25, 0x54, 0x04, 0x48, 0xac,
	0x73, 0xca, 0x1f, 0x25, 0x78, 0xf8, 0x05, 0xb9, 0xb0, 0x4d, 0x87, 0x68, 0x1e, 0x23, 0xbe, 0x4f,
	0x47, 0x69, 0x0b, 0x2d, 0x28, 0x0d, 0xa7, 0x8c, 0x04, 0xcc, 0x27, 0x86, 0xab, 0xfb, 0x24, 0xa0,
	0x13, 0xdf, 0x14, 0x26, 0x16, 0xea, 0x3f, 0xcc, 0x30, 0x91, 0x7a, 0xd5, 0xb8, 0x5c, 0x36, 0xe3,
	0x93, 0x38, 0x3a, 0x78, 0xba, 0x82, 0xd1, 0x70, 0x8e, 0xda, 0xdc, 0x86, 0x2d, 0x8b, 0x38, 0xf6,
	0x25, 0xf1, 0xa7, 0xba, 0x4b, 0xd8, 0x05, 0xb5, 0x94, 0xdf, 0x4b, 0x50, 0xee, 0x0d, 0x1a, 0xa9,
	0xe2, 0xf2, 0xed, 0x6b, 0xf5, 0x8d, 0x04, 0xa5, 0xa6, 0xed, 0x19, 0xfe, 0xf4, 0x7c, 0x6c, 0x19,
	0x8c, 0xf4, 0xc9, 0x28, 0xbc, 0x14, 0xa8, 0x0e, 0xbb, 0xcc, 0xf0, 0x47, 0x84, 0xe9, 0x2e, 0x71,
	0xa9, 0x3f, 0xd5, 0x0d, 0xcb, 0xf2, 0x49, 0x10, 0x70, 0x95, 0xee, 0xe2, 0x92, 0xd8, 0xec, 0xf0,
	0xbd, 0x86, 0xd8, 0x42, 0x65, 0x58, 0x1b, 0x1b, 0x53, 0x87, 0x1a, 0x16, 0xbf, 0x8b, 0x1b, 0xf8,
	0x6a, 0x89, 0x3e, 0x82, 0x3d, 0xcb, 0xb6, 0xf4, 0x54, 0xa6, 0xe8, 0x6c, 0x1a, 0xd5, 0xe5, 0xb0,
	0xba, 0xef, 0x58, 0xb6, 0x95, 0x72, 0xcd, 0x60, 0x3a, 0x26, 0xcd, 0x35, 0xb8, 0x2b, 0x6a, 0xe0,
	0xbf, 0x25, 0x40, 0xa2, 0xb2, 0x27, 0x95, 0x45, 0x0f, 0x60, 0x3d, 0x2a, 0x95, 0xb6, 0x75, 0x55,
	0x03, 0x05, 0x41, 0xb3, 0xd0, 0x21, 0xc8, 0xcf, 0x6d, 0xe2, 0x58, 0x57, 0x16, 0xb8, 0xc6, 0x98,
	0xeb, 0xb5, 0x8e, 0x8b, 0x9c, 0x2e, 0x94, 0xef, 0x18, 0x63, 0xe4, 0xc1, 0xde, 0x90, 0xc3, 0xea,
	0x13, 0x8e, 0xab, 0x07, 0xc2, 0x0b, 0x41, 0x39, 0x7f, 0x90, 0x3f, 0x2c, 0xd4, 0x3f, 0x59, 0x2a,
	0xf3, 0x33, 0xdc, 0x88, 0x77, 0x86, 0xf3, 0xc4, 0x40, 0xf9, 0x4d, 0x1e, 0xee, 0x0b, 0x6b, 0xc4,
	0x46, 0xca, 0xf0, 0xf0, 0xe5, 0x8a, 0xd4, 0x48, 0x5c, 0xbe, 0xe5, 0x5e, 0xae, 0x85, 0xa0, 0x55,
	0x41, 0xe3, 0x37, 0x0f, 0x26, 0xf1, 0x37, 0x1a, 0xc3, 0xa6, 0x3d, 0xf2, 0xec, 0xd9, 0x55, 0xcf,
	0xdd, 0xa0, 0x92, 0x2f, 0x96, 0xa6, 0x45, 0x98, 0x5c, 0xde, 0x86, 0x9d, 0x58, 0x29, 0x9f, 0x02,
	0xcc, 0x74, 0x41, 0x5b, 0x50, 0x38, 0xef, 0xf6, 0xcf, 0xd4, 0x23, 0xed, 0x58, 0x53, 0x5b, 0xf2,
	0x0a, 0xda, 0x84, 0x75, 0xad, 0xd3, 0x51, 0x5b, 0x5a, 0x58, 0xe9, 0x44, 0x75, 0x53, 0xdb, 0x8d,
	0xa7, 0xfc, 0x6e, 0x63, 0xd8, 0x48, 0x02, 0xa7, 0x4b, 0xc3, 0x43, 0x28, 0x37, 0xda, 0xed, 0xde,
	0x13, 0xfd, 0xc9, 0xa9, 0xd6, 0x56, 0x75, 0xed, 0xa4, 0xab, 0x0d, 0xb4, 0x5e, 0x57, 0xef, 0x1d,
	0x1f, 0xcb, 0x12, 0xda, 0x87, 0x12, 0x56, 0x3f, 0x3f, 0xd7, 0x70, 0x72, 0xa7, 0x2b, 0xe7, 0x94,
	0xbf, 0xe5, 0x61, 0xbf, 0x33, 0x71, 0x98, 0x9d, 0x91, 0x5d, 0x4e, 0x56, 0x20, 0x4e, 0x96, 0x73,
	0x4d, 0x36, 0x64, 0x22, 0x0c, 0xcd, 0x5c, 0x59, 0x4a, 0x85, 0xe2, 0x05, 0xec, 0x46, 0xb9, 0x9c,
	0xca, 0xc5, 0xb0, 0xbb, 0x09, 0x73, 0xf0, 0xe3, 0x1b, 0x84, 0x24, 0x29, 0x12, 0x97, 0xdc, 0x39,
	0x5a, 0x80, 0x7e, 0x09, 0x0f, 0x22, 0x61, 0x91, 0x85, 0x29, 0x18, 0x7e, 0x2b, 0x0b, 0xf5, 0xc7,
	0xef, 0x96, 0x05, 0xf8, 0xbe, 0xbb, 0x68, 0xeb, 0x5d, 0xb2, 0xe0, 0x5f, 0x12, 0xc8, 0x71, 0xa3,
	0x72, 0x66, 0x98, 0x2f, 0x8c, 0x11, 0x41, 0xef, 0x43, 0x31, 0xee, 0x69, 0x12, 0x6d, 0x23, 0xde,
	0x8c, 0xa9, 0xbc, 0x6f, 0xfc, 0x95, 0x04, 0x7b, 0xd9, 0x9d, 0x69, 0x94, 0xf8, 0xbd, 0x6b, 0x26,
	0xcf, 0xda, 0xe9, 0x64, 0x77, 0x5b, 0x15, 0x47, 0xb5, 0x08, 0xa2, 0x2f, 0x7a, 0xdb, 0x46, 0x06,
	0x11, 0xef, 0x64, 0xb1, 0x2a, 0x7f, 0x5f, 0x85, 0xc3, 0xd8, 0x86, 0x23, 0xea, 0x38, 0x61, 0x73,
	0x47, 0xbd, 0xec, 0xb7, 0xe1, 0x39, 0x6c, 0xcf, 0x6c, 0x1b, 0x0b, 0x83, 0xcb, 0x12, 0x4f, 0x8a,
	0x9f, 0x2c, 0x15, 0xa1, 0xeb, 0xde, 0xe2, 0xa9, 0x27, 0xb3, 0xeb, 0x3e, 0xfc, 0x83, 0x04, 0xc5,
	0xa8, 0x3f, 0x1c, 0x4e, 0xf5, 0xaf, 0xa8, 0x27, 0xaa, 0x41, 0xa1, 0xee, 0xdd, 0x4c, 0xca, 0x1b,
	0xec, 0xa9, 0xaa, 0x5c, 0x46, 0x73, 0xfa, 0x8c, 0x7a, 0xe9, 0xac, 0x68, 0x11, 0x66, 0xd8, 0x4e,
	0x70, 0xba, 0x82, 0x37, 0x48, 0x82, 0x07, 0xfd, 0x49, 0x82, 0x2d, 0xcb, 0x0e, 0x52, 0x9a, 0x89,
	0x0c, 0xa5, 0xb7, 0xab, 0x59, 0x4b, 0x08, 0x79, 0xad, 0x6a, 0x9b, 0x56, 0x92, 0x29, 0xd4, 0x6d,
	0x37, 0xfd, 0xac, 0x59, 0x82, 0xb5, 0x7c, 0x87, 0x6b, 0x38, 0xbc, 0x5d, 0x0d, 0x17, 0x28, 0xb5,
	0x63, 0x66, 0xd0, 0x2b, 0x0a, 0x1c, 0xbc, 0xc9, 0xd7, 0x95, 0x47, 0xf0, 0xde, 0x1b, 0xad, 0xae,
	0xbc, 0xe2, 0x13, 0xc8, 0x1c, 0x1d, 0x59, 0x80, 0xe6, 0x32, 0x33, 0x78, 0xa7, 0xd4, 0xc4, 0xdb,
	0xd7, 0xd3, 0x32, 0x68, 0xae, 0xc2, 0x9d, 0xb0, 0x55, 0x50, 0xfe, 0x59, 0x80, 0x4a, 0x4a, 0x8d,
	0xa8, 0xc0, 0x45, 0x63, 0xa3, 0xc7, 0x03, 0x11, 0x8f, 0x49, 0x7a, 0x10, 0xf9, 0x2c, 0x6a, 0xa2,
	0x3e, 0x5d, 0x76, 0xf4, 0x9b, 0x1b, 0xb4, 0xb8, 0x77, 0xe7, 0xc7, 0x2f, 0x92, 0x34, 0x3e, 0x16,
	0x26, 0x6e, 0xcc, 0x47, 0x37, 0x33, 0x3e, 0x96, 0x34, 0xb3, 0x3e, 0x16, 0xf3, 0x5b, 0x09, 0xbe,
	0x33, 0x9b, 0xef, 0xf5, 0x0c, 0x91, 0xe2, 0x2a, 0x1c, 0x2f, 0x25, 0x72, 0x86, 0x94, 0xcc, 0xb9,
	0x64, 0xd1, 0x7e, 0x30, 0x63, 0x99, 0x9f, 0x20, 0x5f, 0xc0, 0x0e, 0x99, 0x4d, 0x4e, 0x33, 0x15,
	0x44, 0xae, 0x7f, 0xf2, 0xb6, 0xa3, 0x17, 0x2e, 0x91, 0x8c, 0x59, 0x53, 0x07, 0xd9, 0x14, 0xc3,
	0xcc, 0x4c, 0xd0, 0x5d, 0x2e, 0xe8, 0xc7, 0xcb, 0xc5, 0x32, 0x3d, 0x09, 0xe1, 0x2d, 0xf3, 0xda,
	0x68, 0xf4, 0x25, 0xec, 0xa5, 0x87, 0x9d, 0x58, 0xcc, 0x2a, 0x17, 0xf3, 0xd3, 0xb7, 0x1f, 0x78,
	0xf0, 0xae, 0x91, 0x39, 0x5f, 0xfd, 0x5a, 0x82, 0xef, 0x5e, 0x8a, 0xf1, 0x44, 0xb7, 0x93, 0xf3,
	0xc9, 0x4c, 0xf6, 0x1a, 0x97, 0xdd, 0x58, 0x4a, 0xf6, 0xeb, 0x26, 0x1d, 0xfc, 0xf0, 0xf2, 0x75,
	0x73, 0xd0, 0xd7, 0x50, 0xa1, 0xcc, 0xb8, 0xd6, 0x92, 0xc7, 0x4a, 0xdc, 0xe3, 0x4a, 0xfc, 0x7c,
	0x29, 0x25, 0x16, 0x0d, 0x35, 0xb8, 0x4c, 0x99, 0x91, 0xfd, 0xa4, 0x4d, 0xa1, 0xe2, 0x86, 0x1d,
	0x92, 0x9e, 0xd5, 0xf1, 0x94, 0xd7, 0xb9, 0xf0, 0x9f, 0xbd, 0x4b, 0xa3, 0x85, 0xf7, 0xdd, 0x05,
	0x4d, 0xdd, 0x5f, 0x25, 0xf8, 0x60, 0x76, 0x89, 0xcc, 0xb8, 0xde, 0x2e, 0xf2, 0x04, 0x70, 0x65,
	0x3a, 0xb7, 0x5a, 0xc6, 0xf1, 0x21, 0x5b, 0xf6, 0xf1, 0x7f, 0x05, 0x0f, 0x46, 0x84, 0x3e, 0x27,
	0x9e, 0x49, 0x74, 0xfe, 0xb8, 0x5c, 0xda, 0x26, 0x99, 0x69, 0x57, 0xb8, 0x41, 0x9c, 0x4e, 0x08,
	0x3d, 0x0e, 0x71, 0x7a, 0x5e, 0x8b, 0xa3, 0xcc, 0xe2, 0x74, 0x25, 0xe1, 0xfa, 0x0e, 0x6a, 0xc3,
	0x66, 0xba, 0x31, 0xb4, 0x78, 0x6d, 0xff, 0xde, 0xc2, 0x2e, 0x29, 0x5d, 0x4b, 0xd2, 0x87, 0x95,
	0xff, 0x4a, 0x50, 0x5e, 0xa4, 0x04, 0x72, 0x60, 0xc3, 0x17, 0x95, 0x5c, 0x0c, 0x86, 0x37, 0x19,
	0x7b, 0x16, 0x81, 0x56, 0xa3, 0xb7, 0x21, 0x9c, 0x25, 0x71, 0xc1, 0x9f, 0x2d, 0x94, 0xcf, 0xa1,
	0x90, 0xd8, 0x4b, 0x4f, 0x12, 0x6b, 0x90, 0x6f, 0xb4, 0x5a, 0xb2, 0x84, 0x00, 0x56, 0xcf, 0xcf,
	0x5a, 0x61, 0x0b, 0x9a, 0x0b, 0xbf, 0x5b, 0x6a, 0x5b, 0x1d, 0xa8, 0x72, 0x3e, 0x64, 0x38, 0x51,
	0x07, 0xf2, 0xdd, 0xf0, 0xd8, 0x89, 0x3a, 0xd0, 0xb5, 0x56, 0x5f, 0x5e, 0x6d, 0x7e, 0x23, 0xc1,
	0xf7, 0x4d, 0xea, 0x2e, 0xa3, 0x70, 0x13, 0xa5, 0xfc, 0x74, 0xe6, 0x53, 0x46, 0xcf, 0xa4, 0x67,
	0xcf, 0x46, 0x36, 0xbb, 0x98, 0x0c, 0xc3, 0x33, 0xb5, 0x18, 0xe5, 0x43, 0xc3, 0xae, 0x91, 0x97,
	0x8c, 0xf8, 0x9e, 0xe1, 0x7c, 0xc8, 0x7f, 0x9f, 0x06, 0xb5, 0xc0, 0x37, 0x6b, 0xae, 0x61, 0x7b,
	0x35, 0xbe, 0xae, 0x2d, 0xf1, 0x8b, 0xf8, 0x7f, 0x92, 0xf4, 0xe7, 0x5c, 0xbe, 0x71, 0x3e, 0x18,
	0xae, 0xf2, 0x33, 0x3f, 0xfa, 0x7f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x1d, 0x8f, 0x27, 0x7b, 0xb7,
	0x16, 0x00, 0x00,
}
