/*-
 * ‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾
 * Autonomic Proprietary 1.0
 * ——————————————————————————————————————————————————————————————————————————————
 * Copyright (C) 2020 Autonomic, LLC - All rights reserved
 * ——————————————————————————————————————————————————————————————————————————————
 * Proprietary and confidential.
 *
 * NOTICE:  All information contained herein is, and remains the property of
 * Autonomic, LLC and its suppliers, if any.  The intellectual and technical
 * concepts contained herein are proprietary to Autonomic, LLC and its suppliers
 * and may be covered by U.S. and Foreign Patents, patents in process, and are
 * protected by trade secret or copyright law. Dissemination of this information
 * or reproduction of this material is strictly forbidden unless prior written
 * permission is obtained from Autonomic, LLC.
 *
 * Unauthorized copy of this file, via any medium is strictly prohibited.
 * ______________________________________________________________________________
 */
// Code generated by protoc-gen-go. DO NOT EDIT.
// source: autonomic/ext/telemetry/modules/module.proto

package modules

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ModulePropertyPropertyType int32

const (
	ModuleProperty_UNKNOWN_PROPERTY_TYPE  ModulePropertyPropertyType = 0
	ModuleProperty_DID                    ModulePropertyPropertyType = 1
	ModuleProperty_SUB_COMPENENT_PROPERTY ModulePropertyPropertyType = 2
)

var ModulePropertyPropertyType_name = map[int32]string{
	0: "UNKNOWN_PROPERTY_TYPE",
	1: "DID",
	2: "SUB_COMPENENT_PROPERTY",
}

var ModulePropertyPropertyType_value = map[string]int32{
	"UNKNOWN_PROPERTY_TYPE":  0,
	"DID":                    1,
	"SUB_COMPENENT_PROPERTY": 2,
}

func (x ModulePropertyPropertyType) String() string {
	return proto.EnumName(ModulePropertyPropertyType_name, int32(x))
}

func (ModulePropertyPropertyType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_edd214a74203ff86, []int{0, 0}
}

type ModuleProperty struct {
	Key                  string                     `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string                     `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Type                 ModulePropertyPropertyType `protobuf:"varint,3,opt,name=type,proto3,enum=autonomic.ext.telemetry.ModulePropertyPropertyType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *ModuleProperty) Reset()         { *m = ModuleProperty{} }
func (m *ModuleProperty) String() string { return proto.CompactTextString(m) }
func (*ModuleProperty) ProtoMessage()    {}
func (*ModuleProperty) Descriptor() ([]byte, []int) {
	return fileDescriptor_edd214a74203ff86, []int{0}
}

func (m *ModuleProperty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModuleProperty.Unmarshal(m, b)
}
func (m *ModuleProperty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModuleProperty.Marshal(b, m, deterministic)
}
func (m *ModuleProperty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModuleProperty.Merge(m, src)
}
func (m *ModuleProperty) XXX_Size() int {
	return xxx_messageInfo_ModuleProperty.Size(m)
}
func (m *ModuleProperty) XXX_DiscardUnknown() {
	xxx_messageInfo_ModuleProperty.DiscardUnknown(m)
}

var xxx_messageInfo_ModuleProperty proto.InternalMessageInfo

func (m *ModuleProperty) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *ModuleProperty) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *ModuleProperty) GetType() ModulePropertyPropertyType {
	if m != nil {
		return m.Type
	}
	return ModuleProperty_UNKNOWN_PROPERTY_TYPE
}

// A Module on the vehicle
type Module struct {
	ModuleName string `protobuf:"bytes,1,opt,name=module_name,json=moduleName,proto3" json:"module_name,omitempty"`
	Address    string `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Serial     string `protobuf:"bytes,4,opt,name=serial,proto3" json:"serial,omitempty"`
	// properties of this module
	// (e.g. components, DIDs, etc.)
	Properties           []*ModuleProperty `protobuf:"bytes,5,rep,name=properties,proto3" json:"properties,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Module) Reset()         { *m = Module{} }
func (m *Module) String() string { return proto.CompactTextString(m) }
func (*Module) ProtoMessage()    {}
func (*Module) Descriptor() ([]byte, []int) {
	return fileDescriptor_edd214a74203ff86, []int{1}
}

func (m *Module) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Module.Unmarshal(m, b)
}
func (m *Module) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Module.Marshal(b, m, deterministic)
}
func (m *Module) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Module.Merge(m, src)
}
func (m *Module) XXX_Size() int {
	return xxx_messageInfo_Module.Size(m)
}
func (m *Module) XXX_DiscardUnknown() {
	xxx_messageInfo_Module.DiscardUnknown(m)
}

var xxx_messageInfo_Module proto.InternalMessageInfo

func (m *Module) GetModuleName() string {
	if m != nil {
		return m.ModuleName
	}
	return ""
}

func (m *Module) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Module) GetSerial() string {
	if m != nil {
		return m.Serial
	}
	return ""
}

func (m *Module) GetProperties() []*ModuleProperty {
	if m != nil {
		return m.Properties
	}
	return nil
}

func init() {
	proto.RegisterEnum("autonomic.ext.telemetry.ModulePropertyPropertyType", ModulePropertyPropertyType_name, ModulePropertyPropertyType_value)
	proto.RegisterType((*ModuleProperty)(nil), "autonomic.ext.telemetry.ModuleProperty")
	proto.RegisterType((*Module)(nil), "autonomic.ext.telemetry.Module")
}

func init() {
	proto.RegisterFile("autonomic/ext/telemetry/modules/module.proto", fileDescriptor_edd214a74203ff86)
}

var fileDescriptor_edd214a74203ff86 = []byte{
	// 373 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0xd1, 0xae, 0x93, 0x40,
	0x10, 0x75, 0xcb, 0xbd, 0xbd, 0xb9, 0xd3, 0x78, 0x43, 0x36, 0x7a, 0x45, 0x5f, 0x6c, 0xea, 0x83,
	0x7d, 0xb0, 0x6c, 0x52, 0xe3, 0x07, 0x58, 0x4b, 0x4c, 0x63, 0x0a, 0x04, 0xa9, 0xa6, 0xbe, 0x90,
	0x2d, 0x9d, 0x28, 0x91, 0x65, 0x9b, 0x65, 0x31, 0xe5, 0x43, 0xfc, 0x01, 0xe3, 0x27, 0xf9, 0x31,
	0x3e, 0x1a, 0x16, 0x24, 0xf6, 0xa1, 0xf1, 0x3e, 0x31, 0x67, 0x38, 0x67, 0x66, 0xce, 0xce, 0xc0,
	0x0b, 0x5e, 0x69, 0x59, 0x48, 0x91, 0xa5, 0x0c, 0x8f, 0x9a, 0x69, 0xcc, 0x51, 0xa0, 0x56, 0x35,
	0x13, 0x72, 0x5f, 0xe5, 0x58, 0x76, 0x5f, 0xf7, 0xa0, 0xa4, 0x96, 0xf4, 0x51, 0xcf, 0x76, 0xf1,
	0xa8, 0xdd, 0x9e, 0x3d, 0xf9, 0x45, 0xe0, 0x66, 0x6d, 0x98, 0xa1, 0x92, 0x07, 0x54, 0xba, 0xa6,
	0x36, 0x58, 0x5f, 0xb1, 0x76, 0xc8, 0x98, 0x4c, 0xaf, 0xa3, 0x26, 0xa4, 0x0f, 0xe0, 0xf2, 0x1b,
	0xcf, 0x2b, 0x74, 0x06, 0x26, 0xd7, 0x02, 0xba, 0x82, 0x0b, 0x5d, 0x1f, 0xd0, 0xb1, 0xc6, 0x64,
	0x7a, 0x33, 0x7f, 0xe5, 0x9e, 0x69, 0xe1, 0x9e, 0x96, 0x6f, 0x06, 0x32, 0x41, 0xd2, 0x88, 0x23,
	0x53, 0x62, 0x12, 0xc0, 0xfd, 0x93, 0x34, 0x7d, 0x0c, 0x0f, 0x37, 0xfe, 0x3b, 0x3f, 0xf8, 0xe8,
	0x27, 0x61, 0x14, 0x84, 0x5e, 0x14, 0x6f, 0x93, 0x78, 0x1b, 0x7a, 0xf6, 0x3d, 0x7a, 0x05, 0xd6,
	0x72, 0xb5, 0xb4, 0x09, 0x7d, 0x02, 0xb7, 0xef, 0x37, 0x8b, 0xe4, 0x4d, 0xb0, 0x0e, 0x3d, 0xdf,
	0xf3, 0xe3, 0x9e, 0x69, 0x0f, 0x26, 0x3f, 0x09, 0x0c, 0xdb, 0xbe, 0xf4, 0x29, 0x8c, 0xda, 0xa7,
	0x48, 0x0a, 0x2e, 0xb0, 0xb3, 0x05, 0x6d, 0xca, 0xe7, 0x02, 0xa9, 0x03, 0x57, 0x7c, 0xbf, 0x57,
	0x58, 0x96, 0xc6, 0xca, 0x75, 0xf4, 0x17, 0xd2, 0x5b, 0x18, 0x96, 0xa8, 0x32, 0x9e, 0x3b, 0x17,
	0xe6, 0x47, 0x87, 0xe8, 0x5b, 0x80, 0x6e, 0xdc, 0x0c, 0x4b, 0xe7, 0x72, 0x6c, 0x4d, 0x47, 0xf3,
	0xe7, 0x77, 0xf4, 0x1f, 0xfd, 0x23, 0x5d, 0x7c, 0x27, 0xf0, 0x2c, 0x95, 0xe2, 0xac, 0xb4, 0xdb,
	0xe5, 0x62, 0xd4, 0xd7, 0xd0, 0x32, 0x24, 0x9f, 0x3e, 0x7c, 0xce, 0xf4, 0x97, 0x6a, 0xe7, 0xa6,
	0x52, 0xb0, 0x5e, 0x3a, 0xe3, 0x59, 0x73, 0x09, 0xa8, 0x0a, 0x9e, 0xcf, 0xcc, 0xd6, 0x4b, 0x56,
	0xaa, 0x94, 0x09, 0x9e, 0x15, 0xcc, 0x60, 0xf6, 0x9f, 0x93, 0xf9, 0x4d, 0xc8, 0x8f, 0x81, 0xf5,
	0x7a, 0x13, 0xef, 0x86, 0x86, 0xff, 0xf2, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x65, 0x19, 0x84,
	0x2f, 0x65, 0x02, 0x00, 0x00,
}
