/*-
 * ‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾
 * Autonomic Proprietary 1.0
 * ——————————————————————————————————————————————————————————————————————————————
 * Copyright (C) 2020 Autonomic, LLC - All rights reserved
 * ——————————————————————————————————————————————————————————————————————————————
 * Proprietary and confidential.
 *
 * NOTICE:  All information contained herein is, and remains the property of
 * Autonomic, LLC and its suppliers, if any.  The intellectual and technical
 * concepts contained herein are proprietary to Autonomic, LLC and its suppliers
 * and may be covered by U.S. and Foreign Patents, patents in process, and are
 * protected by trade secret or copyright law. Dissemination of this information
 * or reproduction of this material is strictly forbidden unless prior written
 * permission is obtained from Autonomic, LLC.
 *
 * Unauthorized copy of this file, via any medium is strictly prohibited.
 * ______________________________________________________________________________
 */
// Code generated by protoc-gen-go. DO NOT EDIT.
// source: autonomic/ext/event/state/execute_pending_updates.proto

package state

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type WellKnownExecutePendingUpdatesState int32

const (
	WellKnownExecutePendingUpdatesState_UNKNOWN_STATE WellKnownExecutePendingUpdatesState = 0
	// Request was received by cloud through API
	// Emitted by: cloud
	WellKnownExecutePendingUpdatesState_REQUESTED WellKnownExecutePendingUpdatesState = 1
	// Request was queued in the cloud, waiting for device
	// to connect.
	// Emitted by: cloud
	// Triggered by: REQUEST_QUEUED_FOR_DELIVERY
	WellKnownExecutePendingUpdatesState_REQUEST_DELIVERY_QUEUED WellKnownExecutePendingUpdatesState = 2
	// Cloud attempted delivery of request to device
	// Emitted by: cloud
	// Triggered by: OEM_CLOUD_TRANSLATION_SUCCEEDED
	WellKnownExecutePendingUpdatesState_REQUEST_DELIVERY_IN_PROGRESS WellKnownExecutePendingUpdatesState = 3
	// Delivery of request attempt was not acknowledged by device in a timely fashion
	// Emitted by: cloud
	// Triggered by: REQUEST_DELIVERY_TIMEOUT_EXCEEDED
	WellKnownExecutePendingUpdatesState_REQUEST_DELIVERY_TIMED_OUT WellKnownExecutePendingUpdatesState = 4
	// Delivery of request attempt failed due to device disconnect
	// Emitted by: cloud
	// Triggered by: REQUEST_DELIVERY_FAILED
	WellKnownExecutePendingUpdatesState_REQUEST_DELIVERY_FAILURE WellKnownExecutePendingUpdatesState = 5
	// Request is acknowledged by device, queued, and the device will begin
	// processing the request when the device is ready.
	// Emitted by: device
	// Triggered by: REQUEST_QUEUED_ON_DEVICE
	WellKnownExecutePendingUpdatesState_REQUEST_QUEUED WellKnownExecutePendingUpdatesState = 6
	// Request is being decrypted and validated by device
	// Emitted by: device
	// Triggered by: REQUEST_VALIDATION_STARTED
	WellKnownExecutePendingUpdatesState_REQUEST_VALIDATION_IN_PROGRESS WellKnownExecutePendingUpdatesState = 7
	// Request failed validation or decryption
	// Emitted by: device
	// Triggered by: REQUEST_VALIDATION_FAILED
	WellKnownExecutePendingUpdatesState_REQUEST_VALIDATION_FAILURE WellKnownExecutePendingUpdatesState = 8
	// ExecutePendingUpdates is in the process of being reset
	// Emitted by: device
	// Triggered by: REQUEST_VALIDATION_SUCCEEDED
	WellKnownExecutePendingUpdatesState_PENDING_UPDATES_IN_PROGRESS WellKnownExecutePendingUpdatesState = 9
	// The device has successfully completed the actuation in question.
	// Triggered by: PENDING_UPDATES_SUCCEEDED
	WellKnownExecutePendingUpdatesState_SUCCEEDED_ON_DEVICE WellKnownExecutePendingUpdatesState = 23
	// Oem cloud attempted delivery of request
	// Emitted by: cloud
	// Triggered by: DEVICE_CONNECTED_TO_CLOUD
	WellKnownExecutePendingUpdatesState_OEM_CLOUD_DELIVERY_IN_PROGRESS WellKnownExecutePendingUpdatesState = 10
	// Cloud attempted translation of request
	// Emitted by: cloud
	// Triggered by: OEM_CLOUD_DELIVERY_SUCCEEDED
	WellKnownExecutePendingUpdatesState_OEM_CLOUD_TRANSLATION_IN_PROGRESS WellKnownExecutePendingUpdatesState = 11
	// The cloud is in the process of validating the event emitted by the device indicating that the
	// command has succeeded.
	// Triggered by: SUCCEEDED_ON_DEVICE_EVENT_RECEIVED
	WellKnownExecutePendingUpdatesState_CLOUD_VALIDATION_IN_PROGRESS WellKnownExecutePendingUpdatesState = 24
	// Cloud failed to validate data provided by the device
	// Emitted by: cloud
	// Triggered by: CLOUD_VALIDATION_OF_DEVICE_DATA_FAILED
	WellKnownExecutePendingUpdatesState_CLOUD_VALIDATION_FAILURE WellKnownExecutePendingUpdatesState = 12
	// ExecutePendingUpdates upload succeeded, and the URI(s) of the archive(s) has been
	// added to the event containing this state.
	// This state is terminal
	// Triggered by: CLOUD_VALIDATION_OF_DEVICE_DATA_SUCCEEDED
	WellKnownExecutePendingUpdatesState_SUCCESS WellKnownExecutePendingUpdatesState = 17
	// ExecutePendingUpdates failed. All intermediate failure states should transition to
	// this state.
	// Emitted by: device
	// Triggered by: PENDING_UPDATES_FAILED
	WellKnownExecutePendingUpdatesState_FAILURE WellKnownExecutePendingUpdatesState = 18
	// ExecutePendingUpdates command expired. This event can be emitted by
	// the device or the cloud. In either case, it will cause
	// the command to be removed from the set of in-progress commands
	// on the cloud. However the cloud does not send this event to
	// the device. This state is terminal.
	// Triggered by: EXPIRATION_EXCEEDED
	WellKnownExecutePendingUpdatesState_EXPIRED WellKnownExecutePendingUpdatesState = 19
	// Command is being removed from set of in-progress
	// commands from the cloud. Emitted by cloud.
	// Triggered by: CANCELLATION_REQUEST_ACKNOWLEDGED
	WellKnownExecutePendingUpdatesState_CANCELLATION_IN_PROGRESS WellKnownExecutePendingUpdatesState = 21
	// Command was successfully removed from set of in-progress
	// commands from the cloud. Emitted by cloud.
	// Triggered by: CANCELLATION_REQUEST_FULFILLED
	WellKnownExecutePendingUpdatesState_CANCELLED WellKnownExecutePendingUpdatesState = 22
)

var WellKnownExecutePendingUpdatesState_name = map[int32]string{
	0:  "UNKNOWN_STATE",
	1:  "REQUESTED",
	2:  "REQUEST_DELIVERY_QUEUED",
	3:  "REQUEST_DELIVERY_IN_PROGRESS",
	4:  "REQUEST_DELIVERY_TIMED_OUT",
	5:  "REQUEST_DELIVERY_FAILURE",
	6:  "REQUEST_QUEUED",
	7:  "REQUEST_VALIDATION_IN_PROGRESS",
	8:  "REQUEST_VALIDATION_FAILURE",
	9:  "PENDING_UPDATES_IN_PROGRESS",
	23: "SUCCEEDED_ON_DEVICE",
	10: "OEM_CLOUD_DELIVERY_IN_PROGRESS",
	11: "OEM_CLOUD_TRANSLATION_IN_PROGRESS",
	24: "CLOUD_VALIDATION_IN_PROGRESS",
	12: "CLOUD_VALIDATION_FAILURE",
	17: "SUCCESS",
	18: "FAILURE",
	19: "EXPIRED",
	21: "CANCELLATION_IN_PROGRESS",
	22: "CANCELLED",
}

var WellKnownExecutePendingUpdatesState_value = map[string]int32{
	"UNKNOWN_STATE":                     0,
	"REQUESTED":                         1,
	"REQUEST_DELIVERY_QUEUED":           2,
	"REQUEST_DELIVERY_IN_PROGRESS":      3,
	"REQUEST_DELIVERY_TIMED_OUT":        4,
	"REQUEST_DELIVERY_FAILURE":          5,
	"REQUEST_QUEUED":                    6,
	"REQUEST_VALIDATION_IN_PROGRESS":    7,
	"REQUEST_VALIDATION_FAILURE":        8,
	"PENDING_UPDATES_IN_PROGRESS":       9,
	"SUCCEEDED_ON_DEVICE":               23,
	"OEM_CLOUD_DELIVERY_IN_PROGRESS":    10,
	"OEM_CLOUD_TRANSLATION_IN_PROGRESS": 11,
	"CLOUD_VALIDATION_IN_PROGRESS":      24,
	"CLOUD_VALIDATION_FAILURE":          12,
	"SUCCESS":                           17,
	"FAILURE":                           18,
	"EXPIRED":                           19,
	"CANCELLATION_IN_PROGRESS":          21,
	"CANCELLED":                         22,
}

func (x WellKnownExecutePendingUpdatesState) String() string {
	return proto.EnumName(WellKnownExecutePendingUpdatesState_name, int32(x))
}

func (WellKnownExecutePendingUpdatesState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2c9ab3f858b18a2a, []int{0}
}

// ExecutePendingUpdates state transition triggers. See WellKnownExecutePendingUpdatesState enum
// for documentation on when these triggers occur.
type WellKnownExecutePendingUpdatesTransitionTrigger int32

const (
	WellKnownExecutePendingUpdatesTransitionTrigger_UNKNOWN_TRANSITION_TRIGGER                WellKnownExecutePendingUpdatesTransitionTrigger = 0
	WellKnownExecutePendingUpdatesTransitionTrigger_REQUEST_QUEUED_FOR_DELIVERY               WellKnownExecutePendingUpdatesTransitionTrigger = 1
	WellKnownExecutePendingUpdatesTransitionTrigger_DEVICE_CONNECTED_TO_CLOUD                 WellKnownExecutePendingUpdatesTransitionTrigger = 2
	WellKnownExecutePendingUpdatesTransitionTrigger_REQUEST_DELIVERY_FAILED                   WellKnownExecutePendingUpdatesTransitionTrigger = 3
	WellKnownExecutePendingUpdatesTransitionTrigger_REQUEST_DELIVERY_TIMEOUT_EXCEEDED         WellKnownExecutePendingUpdatesTransitionTrigger = 4
	WellKnownExecutePendingUpdatesTransitionTrigger_REQUEST_QUEUED_ON_DEVICE                  WellKnownExecutePendingUpdatesTransitionTrigger = 5
	WellKnownExecutePendingUpdatesTransitionTrigger_REQUEST_VALIDATION_STARTED                WellKnownExecutePendingUpdatesTransitionTrigger = 6
	WellKnownExecutePendingUpdatesTransitionTrigger_REQUEST_VALIDATION_FAILED                 WellKnownExecutePendingUpdatesTransitionTrigger = 7
	WellKnownExecutePendingUpdatesTransitionTrigger_REQUEST_VALIDATION_SUCCEEDED              WellKnownExecutePendingUpdatesTransitionTrigger = 23
	WellKnownExecutePendingUpdatesTransitionTrigger_PENDING_UPDATES_STARTED                   WellKnownExecutePendingUpdatesTransitionTrigger = 8
	WellKnownExecutePendingUpdatesTransitionTrigger_PENDING_UPDATES_SUCCEEDED                 WellKnownExecutePendingUpdatesTransitionTrigger = 9
	WellKnownExecutePendingUpdatesTransitionTrigger_PENDING_UPDATES_FAILED                    WellKnownExecutePendingUpdatesTransitionTrigger = 10
	WellKnownExecutePendingUpdatesTransitionTrigger_OEM_CLOUD_DELIVERY_SUCCEEDED              WellKnownExecutePendingUpdatesTransitionTrigger = 11
	WellKnownExecutePendingUpdatesTransitionTrigger_OEM_CLOUD_TRANSLATION_SUCCEEDED           WellKnownExecutePendingUpdatesTransitionTrigger = 12
	WellKnownExecutePendingUpdatesTransitionTrigger_SUCCEEDED_ON_DEVICE_EVENT_RECEIVED        WellKnownExecutePendingUpdatesTransitionTrigger = 24
	WellKnownExecutePendingUpdatesTransitionTrigger_CLOUD_VALIDATION_OF_DEVICE_DATA_SUCCEEDED WellKnownExecutePendingUpdatesTransitionTrigger = 13
	WellKnownExecutePendingUpdatesTransitionTrigger_CLOUD_VALIDATION_OF_DEVICE_DATA_FAILED    WellKnownExecutePendingUpdatesTransitionTrigger = 14
	WellKnownExecutePendingUpdatesTransitionTrigger_FAILED                                    WellKnownExecutePendingUpdatesTransitionTrigger = 19
	WellKnownExecutePendingUpdatesTransitionTrigger_EXPIRATION_EXCEEDED                       WellKnownExecutePendingUpdatesTransitionTrigger = 20
	WellKnownExecutePendingUpdatesTransitionTrigger_CANCELLATION_REQUESTED                    WellKnownExecutePendingUpdatesTransitionTrigger = 21
	WellKnownExecutePendingUpdatesTransitionTrigger_CANCELLATION_REQUEST_FULFILLED            WellKnownExecutePendingUpdatesTransitionTrigger = 22
)

var WellKnownExecutePendingUpdatesTransitionTrigger_name = map[int32]string{
	0:  "UNKNOWN_TRANSITION_TRIGGER",
	1:  "REQUEST_QUEUED_FOR_DELIVERY",
	2:  "DEVICE_CONNECTED_TO_CLOUD",
	3:  "REQUEST_DELIVERY_FAILED",
	4:  "REQUEST_DELIVERY_TIMEOUT_EXCEEDED",
	5:  "REQUEST_QUEUED_ON_DEVICE",
	6:  "REQUEST_VALIDATION_STARTED",
	7:  "REQUEST_VALIDATION_FAILED",
	23: "REQUEST_VALIDATION_SUCCEEDED",
	8:  "PENDING_UPDATES_STARTED",
	9:  "PENDING_UPDATES_SUCCEEDED",
	10: "PENDING_UPDATES_FAILED",
	11: "OEM_CLOUD_DELIVERY_SUCCEEDED",
	12: "OEM_CLOUD_TRANSLATION_SUCCEEDED",
	24: "SUCCEEDED_ON_DEVICE_EVENT_RECEIVED",
	13: "CLOUD_VALIDATION_OF_DEVICE_DATA_SUCCEEDED",
	14: "CLOUD_VALIDATION_OF_DEVICE_DATA_FAILED",
	19: "FAILED",
	20: "EXPIRATION_EXCEEDED",
	21: "CANCELLATION_REQUESTED",
	22: "CANCELLATION_REQUEST_FULFILLED",
}

var WellKnownExecutePendingUpdatesTransitionTrigger_value = map[string]int32{
	"UNKNOWN_TRANSITION_TRIGGER":                0,
	"REQUEST_QUEUED_FOR_DELIVERY":               1,
	"DEVICE_CONNECTED_TO_CLOUD":                 2,
	"REQUEST_DELIVERY_FAILED":                   3,
	"REQUEST_DELIVERY_TIMEOUT_EXCEEDED":         4,
	"REQUEST_QUEUED_ON_DEVICE":                  5,
	"REQUEST_VALIDATION_STARTED":                6,
	"REQUEST_VALIDATION_FAILED":                 7,
	"REQUEST_VALIDATION_SUCCEEDED":              23,
	"PENDING_UPDATES_STARTED":                   8,
	"PENDING_UPDATES_SUCCEEDED":                 9,
	"PENDING_UPDATES_FAILED":                    10,
	"OEM_CLOUD_DELIVERY_SUCCEEDED":              11,
	"OEM_CLOUD_TRANSLATION_SUCCEEDED":           12,
	"SUCCEEDED_ON_DEVICE_EVENT_RECEIVED":        24,
	"CLOUD_VALIDATION_OF_DEVICE_DATA_SUCCEEDED": 13,
	"CLOUD_VALIDATION_OF_DEVICE_DATA_FAILED":    14,
	"FAILED":                                    19,
	"EXPIRATION_EXCEEDED":                       20,
	"CANCELLATION_REQUESTED":                    21,
	"CANCELLATION_REQUEST_FULFILLED":            22,
}

func (x WellKnownExecutePendingUpdatesTransitionTrigger) String() string {
	return proto.EnumName(WellKnownExecutePendingUpdatesTransitionTrigger_name, int32(x))
}

func (WellKnownExecutePendingUpdatesTransitionTrigger) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2c9ab3f858b18a2a, []int{1}
}

func init() {
	proto.RegisterEnum("autonomic.ext.event.state.executependingupdates.WellKnownExecutePendingUpdatesState", WellKnownExecutePendingUpdatesState_name, WellKnownExecutePendingUpdatesState_value)
	proto.RegisterEnum("autonomic.ext.event.state.executependingupdates.WellKnownExecutePendingUpdatesTransitionTrigger", WellKnownExecutePendingUpdatesTransitionTrigger_name, WellKnownExecutePendingUpdatesTransitionTrigger_value)
}

func init() {
	proto.RegisterFile("autonomic/ext/event/state/execute_pending_updates.proto", fileDescriptor_2c9ab3f858b18a2a)
}

var fileDescriptor_2c9ab3f858b18a2a = []byte{
	// 693 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x55, 0xdb, 0x4e, 0xdb, 0x40,
	0x10, 0x25, 0xdc, 0x19, 0x2e, 0x5a, 0x96, 0x42, 0xb8, 0xd3, 0x82, 0x8a, 0x5a, 0x24, 0xe2, 0x07,
	0x1e, 0xfa, 0x6c, 0xbc, 0x93, 0xc8, 0x22, 0xd8, 0xc6, 0x5e, 0x07, 0xda, 0x97, 0x55, 0x08, 0x56,
	0x6a, 0x89, 0xd8, 0x28, 0x71, 0x5a, 0xbe, 0xa7, 0xff, 0xd0, 0xb7, 0xfe, 0x49, 0x7f, 0xa4, 0x8f,
	0xd5, 0xfa, 0x92, 0x0b, 0x76, 0x7a, 0x79, 0xcb, 0x66, 0xce, 0x99, 0xd9, 0x39, 0x73, 0x76, 0x0c,
	0x1f, 0x9a, 0xfd, 0x28, 0x0c, 0xc2, 0x8e, 0xdf, 0x52, 0xbc, 0xe7, 0x48, 0xf1, 0xbe, 0x78, 0x41,
	0xa4, 0xf4, 0xa2, 0x66, 0xe4, 0x29, 0xde, 0xb3, 0xd7, 0xea, 0x47, 0x9e, 0x78, 0xf2, 0x82, 0x07,
	0x3f, 0x68, 0x8b, 0xfe, 0xd3, 0x43, 0x33, 0xf2, 0x7a, 0x95, 0xa7, 0x6e, 0x18, 0x85, 0x54, 0x19,
	0x10, 0x2b, 0xde, 0x73, 0x54, 0x89, 0x89, 0x95, 0x98, 0x58, 0x49, 0x89, 0x29, 0x2f, 0xa5, 0x9d,
	0x7d, 0x9f, 0x85, 0x93, 0x5b, 0xef, 0xf1, 0xf1, 0x2a, 0x08, 0xbf, 0x06, 0x98, 0x40, 0xac, 0x04,
	0xe2, 0x26, 0x10, 0x47, 0xb2, 0xe9, 0x3a, 0xac, 0xba, 0xc6, 0x95, 0x61, 0xde, 0x1a, 0xc2, 0xe1,
	0x2a, 0x47, 0x32, 0x45, 0x57, 0x61, 0xc9, 0xc6, 0x1b, 0x17, 0x1d, 0x8e, 0x8c, 0x94, 0xe8, 0x1e,
	0x94, 0xd3, 0xa3, 0x60, 0x58, 0xd7, 0x1b, 0x68, 0x7f, 0x14, 0x37, 0x2e, 0xba, 0xc8, 0xc8, 0x34,
	0x7d, 0x0d, 0xfb, 0xb9, 0xa0, 0x6e, 0x08, 0xcb, 0x36, 0x6b, 0x36, 0x3a, 0x0e, 0x99, 0xa1, 0x87,
	0xb0, 0x9b, 0x43, 0x70, 0xfd, 0x1a, 0x99, 0x30, 0x5d, 0x4e, 0x66, 0xe9, 0x3e, 0x6c, 0xe7, 0xe2,
	0x55, 0x55, 0xaf, 0xbb, 0x36, 0x92, 0x39, 0x4a, 0x61, 0x2d, 0x8b, 0xa6, 0x35, 0xe7, 0xe9, 0x31,
	0x1c, 0x66, 0xff, 0x35, 0xd4, 0xba, 0xce, 0x54, 0xae, 0x9b, 0xc6, 0x58, 0xd5, 0x85, 0xd1, 0xaa,
	0x23, 0x98, 0x2c, 0xef, 0x22, 0x3d, 0x82, 0x3d, 0x0b, 0x0d, 0xa6, 0x1b, 0x35, 0xe1, 0x5a, 0x4c,
	0xe5, 0xe8, 0x8c, 0x25, 0x58, 0xa2, 0x65, 0xd8, 0x70, 0x5c, 0x4d, 0x43, 0x64, 0xf2, 0xa6, 0x86,
	0x60, 0xd8, 0xd0, 0x35, 0x24, 0x65, 0x59, 0xdd, 0xc4, 0x6b, 0xa1, 0xd5, 0x4d, 0x97, 0x15, 0xf7,
	0x0c, 0xf4, 0x2d, 0xbc, 0x19, 0x62, 0xb8, 0xad, 0x1a, 0x4e, 0x3d, 0x7f, 0xc9, 0x65, 0x29, 0x5e,
	0x02, 0x99, 0xd0, 0xc6, 0xb6, 0x14, 0x27, 0x87, 0xc8, 0x9a, 0x58, 0xa1, 0xcb, 0xb0, 0x10, 0xdf,
	0xd1, 0x71, 0xc8, 0xba, 0x3c, 0x64, 0x11, 0x2a, 0x0f, 0x78, 0x67, 0xe9, 0x36, 0x32, 0xb2, 0x11,
	0x27, 0x51, 0x0d, 0x0d, 0xeb, 0x05, 0x97, 0xd8, 0x94, 0xd3, 0x4e, 0xa3, 0xc8, 0xc8, 0xd6, 0xd9,
	0xcf, 0x39, 0x50, 0xfe, 0xec, 0x1b, 0xde, 0x6d, 0x06, 0x3d, 0x3f, 0xf2, 0xc3, 0x80, 0x77, 0xfd,
	0x76, 0xdb, 0xeb, 0x4a, 0xb1, 0x33, 0x0f, 0xc5, 0xcd, 0xea, 0x71, 0x19, 0x6e, 0xeb, 0xb5, 0x1a,
	0xda, 0x64, 0x4a, 0x8a, 0x3d, 0x3e, 0x44, 0x51, 0x35, 0xed, 0x81, 0x76, 0xa4, 0x44, 0x0f, 0x60,
	0x27, 0xd1, 0x57, 0x68, 0xa6, 0x61, 0xa0, 0xc6, 0x91, 0x09, 0x6e, 0x26, 0xfa, 0x91, 0xe9, 0x42,
	0x07, 0xca, 0x5e, 0x91, 0x91, 0x19, 0xa9, 0x75, 0xa1, 0xbf, 0x4c, 0x97, 0x0b, 0xbc, 0x4b, 0x06,
	0x38, 0x6e, 0xb3, 0xf4, 0x0e, 0xc3, 0xa1, 0xce, 0x4d, 0xb0, 0x8b, 0xc3, 0x55, 0x9b, 0xc7, 0x96,
	0x3b, 0x80, 0x9d, 0x09, 0x76, 0x42, 0x46, 0x16, 0x46, 0x5f, 0xc1, 0x28, 0x3d, 0xf3, 0x0f, 0x29,
	0xcb, 0x16, 0x5e, 0xfa, 0x2d, 0xcb, 0xbe, 0x28, 0xb3, 0xe7, 0x82, 0x03, 0xee, 0x12, 0xdd, 0x85,
	0xad, 0x97, 0xe1, 0xb4, 0x32, 0xc8, 0xca, 0x05, 0x6e, 0x1c, 0xb2, 0x97, 0xe9, 0x09, 0x1c, 0x15,
	0x7b, 0x71, 0x08, 0x5a, 0xa1, 0xa7, 0x70, 0x5c, 0xe0, 0x76, 0x81, 0x0d, 0x34, 0xb8, 0xb0, 0x51,
	0x43, 0xbd, 0x81, 0x8c, 0x6c, 0xd3, 0x73, 0x78, 0x9f, 0xf3, 0xa3, 0x59, 0xcd, 0xe0, 0x4c, 0xe5,
	0xea, 0x48, 0xda, 0x55, 0x7a, 0x06, 0xa7, 0x7f, 0x83, 0xa7, 0x9d, 0xac, 0x51, 0x80, 0xf9, 0xf4,
	0xf7, 0x86, 0x7c, 0x7c, 0xb1, 0x7d, 0x13, 0xc6, 0x60, 0x8a, 0xaf, 0xa4, 0x14, 0x63, 0x56, 0x1e,
	0xee, 0xa9, 0x4d, 0xf9, 0x30, 0x8b, 0x62, 0xa2, 0xea, 0xd6, 0xab, 0x7a, 0xe2, 0xee, 0xcb, 0x1f,
	0x25, 0xb8, 0x68, 0x85, 0x9d, 0xca, 0x7f, 0x6e, 0xd3, 0xcb, 0x77, 0xff, 0xb0, 0x4a, 0x2d, 0xb9,
	0xa8, 0xad, 0xd2, 0x27, 0xab, 0xed, 0x47, 0x9f, 0xfb, 0xf7, 0x95, 0x56, 0xd8, 0x19, 0x6e, 0xed,
	0xf3, 0xa6, 0x2f, 0x37, 0xbe, 0xd7, 0x0d, 0x9a, 0x8f, 0xe7, 0xf1, 0x4a, 0xef, 0x29, 0xbd, 0x6e,
	0x4b, 0xe9, 0x34, 0xfd, 0x40, 0x89, 0xcf, 0xca, 0xc4, 0x4f, 0xc3, 0xaf, 0x52, 0xe9, 0xdb, 0xf4,
	0x8c, 0xea, 0xf2, 0xfb, 0xf9, 0x18, 0x79, 0xf1, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x12, 0xd7, 0xc9,
	0x22, 0x47, 0x06, 0x00, 0x00,
}
