/*-
 * ‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾
 * Autonomic Proprietary 1.0
 * ——————————————————————————————————————————————————————————————————————————————
 * Copyright (C) 2020 Autonomic, LLC - All rights reserved
 * ——————————————————————————————————————————————————————————————————————————————
 * Proprietary and confidential.
 *
 * NOTICE:  All information contained herein is, and remains the property of
 * Autonomic, LLC and its suppliers, if any.  The intellectual and technical
 * concepts contained herein are proprietary to Autonomic, LLC and its suppliers
 * and may be covered by U.S. and Foreign Patents, patents in process, and are
 * protected by trade secret or copyright law. Dissemination of this information
 * or reproduction of this material is strictly forbidden unless prior written
 * permission is obtained from Autonomic, LLC.
 *
 * Unauthorized copy of this file, via any medium is strictly prohibited.
 * ______________________________________________________________________________
 */
// Code generated by protoc-gen-go. DO NOT EDIT.
// source: autonomic/ext/deployment/device_deployment.proto

package deployment

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ArtifactReference struct {
	Uri                  string   `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ArtifactReference) Reset()         { *m = ArtifactReference{} }
func (m *ArtifactReference) String() string { return proto.CompactTextString(m) }
func (*ArtifactReference) ProtoMessage()    {}
func (*ArtifactReference) Descriptor() ([]byte, []int) {
	return fileDescriptor_1aad155d0b090c23, []int{0}
}

func (m *ArtifactReference) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArtifactReference.Unmarshal(m, b)
}
func (m *ArtifactReference) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArtifactReference.Marshal(b, m, deterministic)
}
func (m *ArtifactReference) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArtifactReference.Merge(m, src)
}
func (m *ArtifactReference) XXX_Size() int {
	return xxx_messageInfo_ArtifactReference.Size(m)
}
func (m *ArtifactReference) XXX_DiscardUnknown() {
	xxx_messageInfo_ArtifactReference.DiscardUnknown(m)
}

var xxx_messageInfo_ArtifactReference proto.InternalMessageInfo

func (m *ArtifactReference) GetUri() string {
	if m != nil {
		return m.Uri
	}
	return ""
}

func (m *ArtifactReference) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

// Request to register a PID as a device willing to fulfill deployment requests
type RegisterDeploymentListenerRequest struct {
	// TODO: vin and esn should be extracted from certificate, this should be eventually empty
	Vin                  string   `protobuf:"bytes,1,opt,name=vin,proto3" json:"vin,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterDeploymentListenerRequest) Reset()         { *m = RegisterDeploymentListenerRequest{} }
func (m *RegisterDeploymentListenerRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterDeploymentListenerRequest) ProtoMessage()    {}
func (*RegisterDeploymentListenerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1aad155d0b090c23, []int{1}
}

func (m *RegisterDeploymentListenerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterDeploymentListenerRequest.Unmarshal(m, b)
}
func (m *RegisterDeploymentListenerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterDeploymentListenerRequest.Marshal(b, m, deterministic)
}
func (m *RegisterDeploymentListenerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterDeploymentListenerRequest.Merge(m, src)
}
func (m *RegisterDeploymentListenerRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterDeploymentListenerRequest.Size(m)
}
func (m *RegisterDeploymentListenerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterDeploymentListenerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterDeploymentListenerRequest proto.InternalMessageInfo

func (m *RegisterDeploymentListenerRequest) GetVin() string {
	if m != nil {
		return m.Vin
	}
	return ""
}

// A request that a device reconfigure itself with the specified TargetBundle
type DeviceDeploymentRequest struct {
	CorrelationId []byte `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	// The most common use case here is that a request contains exactly one artifact,
	// which represents a controltech manifest.
	Artifacts []*ArtifactReference `protobuf:"bytes,2,rep,name=artifacts,proto3" json:"artifacts,omitempty"`
	// Deprecated: use oem_correlation_id in the CommandTrigger message.
	OemCorrelationId     []byte   `protobuf:"bytes,3,opt,name=oem_correlation_id,json=oemCorrelationId,proto3" json:"oem_correlation_id,omitempty"` // Deprecated: Do not use.
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeviceDeploymentRequest) Reset()         { *m = DeviceDeploymentRequest{} }
func (m *DeviceDeploymentRequest) String() string { return proto.CompactTextString(m) }
func (*DeviceDeploymentRequest) ProtoMessage()    {}
func (*DeviceDeploymentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1aad155d0b090c23, []int{2}
}

func (m *DeviceDeploymentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceDeploymentRequest.Unmarshal(m, b)
}
func (m *DeviceDeploymentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceDeploymentRequest.Marshal(b, m, deterministic)
}
func (m *DeviceDeploymentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceDeploymentRequest.Merge(m, src)
}
func (m *DeviceDeploymentRequest) XXX_Size() int {
	return xxx_messageInfo_DeviceDeploymentRequest.Size(m)
}
func (m *DeviceDeploymentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceDeploymentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceDeploymentRequest proto.InternalMessageInfo

func (m *DeviceDeploymentRequest) GetCorrelationId() []byte {
	if m != nil {
		return m.CorrelationId
	}
	return nil
}

func (m *DeviceDeploymentRequest) GetArtifacts() []*ArtifactReference {
	if m != nil {
		return m.Artifacts
	}
	return nil
}

// Deprecated: Do not use.
func (m *DeviceDeploymentRequest) GetOemCorrelationId() []byte {
	if m != nil {
		return m.OemCorrelationId
	}
	return nil
}

type DeviceDeploymentRequestEnvelope struct {
	// Types that are valid to be assigned to Request:
	//	*DeviceDeploymentRequestEnvelope_DeploymentRequest
	//	*DeviceDeploymentRequestEnvelope_EncryptedRequest
	Request              isDeviceDeploymentRequestEnvelope_Request `protobuf_oneof:"request"`
	XXX_NoUnkeyedLiteral struct{}                                  `json:"-"`
	XXX_unrecognized     []byte                                    `json:"-"`
	XXX_sizecache        int32                                     `json:"-"`
}

func (m *DeviceDeploymentRequestEnvelope) Reset()         { *m = DeviceDeploymentRequestEnvelope{} }
func (m *DeviceDeploymentRequestEnvelope) String() string { return proto.CompactTextString(m) }
func (*DeviceDeploymentRequestEnvelope) ProtoMessage()    {}
func (*DeviceDeploymentRequestEnvelope) Descriptor() ([]byte, []int) {
	return fileDescriptor_1aad155d0b090c23, []int{3}
}

func (m *DeviceDeploymentRequestEnvelope) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceDeploymentRequestEnvelope.Unmarshal(m, b)
}
func (m *DeviceDeploymentRequestEnvelope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceDeploymentRequestEnvelope.Marshal(b, m, deterministic)
}
func (m *DeviceDeploymentRequestEnvelope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceDeploymentRequestEnvelope.Merge(m, src)
}
func (m *DeviceDeploymentRequestEnvelope) XXX_Size() int {
	return xxx_messageInfo_DeviceDeploymentRequestEnvelope.Size(m)
}
func (m *DeviceDeploymentRequestEnvelope) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceDeploymentRequestEnvelope.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceDeploymentRequestEnvelope proto.InternalMessageInfo

type isDeviceDeploymentRequestEnvelope_Request interface {
	isDeviceDeploymentRequestEnvelope_Request()
}

type DeviceDeploymentRequestEnvelope_DeploymentRequest struct {
	DeploymentRequest *DeviceDeploymentRequest `protobuf:"bytes,1,opt,name=deployment_request,json=deploymentRequest,proto3,oneof"`
}

type DeviceDeploymentRequestEnvelope_EncryptedRequest struct {
	EncryptedRequest []byte `protobuf:"bytes,2,opt,name=encrypted_request,json=encryptedRequest,proto3,oneof"`
}

func (*DeviceDeploymentRequestEnvelope_DeploymentRequest) isDeviceDeploymentRequestEnvelope_Request() {
}

func (*DeviceDeploymentRequestEnvelope_EncryptedRequest) isDeviceDeploymentRequestEnvelope_Request() {}

func (m *DeviceDeploymentRequestEnvelope) GetRequest() isDeviceDeploymentRequestEnvelope_Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *DeviceDeploymentRequestEnvelope) GetDeploymentRequest() *DeviceDeploymentRequest {
	if x, ok := m.GetRequest().(*DeviceDeploymentRequestEnvelope_DeploymentRequest); ok {
		return x.DeploymentRequest
	}
	return nil
}

func (m *DeviceDeploymentRequestEnvelope) GetEncryptedRequest() []byte {
	if x, ok := m.GetRequest().(*DeviceDeploymentRequestEnvelope_EncryptedRequest); ok {
		return x.EncryptedRequest
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*DeviceDeploymentRequestEnvelope) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*DeviceDeploymentRequestEnvelope_DeploymentRequest)(nil),
		(*DeviceDeploymentRequestEnvelope_EncryptedRequest)(nil),
	}
}

func init() {
	proto.RegisterType((*ArtifactReference)(nil), "autonomic.ext.deployment.ArtifactReference")
	proto.RegisterType((*RegisterDeploymentListenerRequest)(nil), "autonomic.ext.deployment.RegisterDeploymentListenerRequest")
	proto.RegisterType((*DeviceDeploymentRequest)(nil), "autonomic.ext.deployment.DeviceDeploymentRequest")
	proto.RegisterType((*DeviceDeploymentRequestEnvelope)(nil), "autonomic.ext.deployment.DeviceDeploymentRequestEnvelope")
}

func init() {
	proto.RegisterFile("autonomic/ext/deployment/device_deployment.proto", fileDescriptor_1aad155d0b090c23)
}

var fileDescriptor_1aad155d0b090c23 = []byte{
	// 423 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0x4f, 0x6b, 0xd4, 0x40,
	0x14, 0xdf, 0xd9, 0x15, 0x65, 0x5f, 0xab, 0x64, 0x07, 0xc4, 0x50, 0x04, 0x6b, 0x40, 0x28, 0xc8,
	0x26, 0xeb, 0x8a, 0x87, 0xe2, 0xa9, 0xb1, 0x42, 0x0b, 0x82, 0x65, 0xd0, 0x8b, 0x97, 0x90, 0x9d,
	0xbc, 0xd6, 0x81, 0x64, 0x26, 0x4e, 0x26, 0xa1, 0xfb, 0x31, 0xbc, 0x79, 0xf6, 0xee, 0x47, 0x10,
	0xbf, 0x96, 0x47, 0x99, 0x71, 0x37, 0x29, 0x5b, 0x06, 0xf1, 0xf6, 0xe6, 0xbd, 0xf7, 0xfb, 0xf3,
	0x66, 0xe6, 0xc1, 0x22, 0x6f, 0x8d, 0x92, 0xaa, 0x12, 0x3c, 0xc1, 0x6b, 0x93, 0x14, 0x58, 0x97,
	0x6a, 0x5d, 0xa1, 0xb4, 0x61, 0x27, 0x38, 0x66, 0x43, 0x26, 0xae, 0xb5, 0x32, 0x8a, 0x86, 0x3d,
	0x22, 0xc6, 0x6b, 0x13, 0x0f, 0xf5, 0xe8, 0x18, 0x66, 0x27, 0xda, 0x88, 0xcb, 0x9c, 0x1b, 0x86,
	0x97, 0xa8, 0x51, 0x72, 0xa4, 0x01, 0x4c, 0x5a, 0x2d, 0x42, 0x72, 0x48, 0x8e, 0xa6, 0xcc, 0x86,
	0x94, 0xc2, 0x1d, 0xb3, 0xae, 0x31, 0x1c, 0xbb, 0x94, 0x8b, 0xa3, 0x57, 0xf0, 0x94, 0xe1, 0x95,
	0x68, 0x0c, 0xea, 0xd3, 0x9e, 0xf0, 0x9d, 0x3d, 0x4b, 0xd4, 0x0c, 0xbf, 0xb4, 0xd8, 0x18, 0x4b,
	0xd5, 0x09, 0xb9, 0xa5, 0xea, 0x84, 0x8c, 0x7e, 0x12, 0x78, 0x74, 0xea, 0x7c, 0x0e, 0xa8, 0x6d,
	0xf7, 0x33, 0x78, 0xc0, 0x95, 0xd6, 0x58, 0xe6, 0x46, 0x28, 0x99, 0x89, 0xc2, 0x01, 0xf7, 0xd9,
	0xfd, 0x1b, 0xd9, 0xf3, 0x82, 0x9e, 0xc3, 0x34, 0xdf, 0x98, 0x6e, 0xc2, 0xf1, 0xe1, 0xe4, 0x68,
	0x6f, 0xf9, 0x3c, 0xf6, 0x8d, 0x18, 0xdf, 0x9a, 0x8f, 0x0d, 0x68, 0xba, 0x00, 0xaa, 0xb0, 0xca,
	0x76, 0x54, 0x27, 0x56, 0x35, 0x1d, 0x87, 0x84, 0x05, 0x0a, 0xab, 0x37, 0x37, 0xc5, 0xa3, 0x5f,
	0x04, 0x9e, 0x78, 0xfc, 0xbf, 0x95, 0x1d, 0x96, 0xaa, 0x46, 0xba, 0x02, 0x3a, 0x18, 0xc8, 0xf4,
	0xdf, 0xaa, 0x9b, 0x65, 0x6f, 0xf9, 0xc2, 0xef, 0xd4, 0x43, 0x7b, 0x36, 0x62, 0xb3, 0xe2, 0xd6,
	0x5d, 0xcd, 0x61, 0x86, 0x92, 0xeb, 0x75, 0x6d, 0xb0, 0xe8, 0x25, 0xec, 0xfb, 0xec, 0x9f, 0x8d,
	0x58, 0xd0, 0x97, 0x36, 0xed, 0xe9, 0x14, 0xee, 0x6d, 0x9a, 0x96, 0x3f, 0x08, 0x04, 0xbb, 0x52,
	0xf4, 0x1b, 0x81, 0x03, 0xff, 0x73, 0xd2, 0xd7, 0x7e, 0xd7, 0xff, 0xfc, 0x04, 0x07, 0xc7, 0xff,
	0x3d, 0xf2, 0xf6, 0x26, 0xa3, 0xd1, 0x82, 0xa4, 0x5f, 0x09, 0x3c, 0xe6, 0xaa, 0xf2, 0x92, 0xa4,
	0x0f, 0x77, 0x59, 0x2e, 0xec, 0xaf, 0xbf, 0x20, 0x9f, 0xde, 0x5f, 0x09, 0xf3, 0xb9, 0x5d, 0xc5,
	0x5c, 0x55, 0x49, 0x8f, 0x9e, 0xe7, 0xc2, 0xee, 0x0d, 0x6a, 0x99, 0x97, 0x73, 0xb7, 0x1f, 0x4d,
	0xd2, 0x68, 0x9e, 0x54, 0xb9, 0x90, 0x89, 0x3b, 0x27, 0xbe, 0x05, 0xfb, 0x4d, 0xc8, 0xf7, 0xf1,
	0xe4, 0xe4, 0xe3, 0x87, 0xd5, 0x5d, 0xd7, 0xf8, 0xf2, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x22,
	0x00, 0xb3, 0x9d, 0x8c, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DeviceDeploymentClient is the client API for DeviceDeployment service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DeviceDeploymentClient interface {
	RegisterDeploymentListener(ctx context.Context, in *RegisterDeploymentListenerRequest, opts ...grpc.CallOption) (DeviceDeployment_RegisterDeploymentListenerClient, error)
}

type deviceDeploymentClient struct {
	cc grpc.ClientConnInterface
}

func NewDeviceDeploymentClient(cc grpc.ClientConnInterface) DeviceDeploymentClient {
	return &deviceDeploymentClient{cc}
}

func (c *deviceDeploymentClient) RegisterDeploymentListener(ctx context.Context, in *RegisterDeploymentListenerRequest, opts ...grpc.CallOption) (DeviceDeployment_RegisterDeploymentListenerClient, error) {
	stream, err := c.cc.NewStream(ctx, &_DeviceDeployment_serviceDesc.Streams[0], "/autonomic.ext.deployment.DeviceDeployment/RegisterDeploymentListener", opts...)
	if err != nil {
		return nil, err
	}
	x := &deviceDeploymentRegisterDeploymentListenerClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type DeviceDeployment_RegisterDeploymentListenerClient interface {
	Recv() (*DeviceDeploymentRequestEnvelope, error)
	grpc.ClientStream
}

type deviceDeploymentRegisterDeploymentListenerClient struct {
	grpc.ClientStream
}

func (x *deviceDeploymentRegisterDeploymentListenerClient) Recv() (*DeviceDeploymentRequestEnvelope, error) {
	m := new(DeviceDeploymentRequestEnvelope)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// DeviceDeploymentServer is the server API for DeviceDeployment service.
type DeviceDeploymentServer interface {
	RegisterDeploymentListener(*RegisterDeploymentListenerRequest, DeviceDeployment_RegisterDeploymentListenerServer) error
}

// UnimplementedDeviceDeploymentServer can be embedded to have forward compatible implementations.
type UnimplementedDeviceDeploymentServer struct {
}

func (*UnimplementedDeviceDeploymentServer) RegisterDeploymentListener(req *RegisterDeploymentListenerRequest, srv DeviceDeployment_RegisterDeploymentListenerServer) error {
	return status.Errorf(codes.Unimplemented, "method RegisterDeploymentListener not implemented")
}

func RegisterDeviceDeploymentServer(s *grpc.Server, srv DeviceDeploymentServer) {
	s.RegisterService(&_DeviceDeployment_serviceDesc, srv)
}

func _DeviceDeployment_RegisterDeploymentListener_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RegisterDeploymentListenerRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DeviceDeploymentServer).RegisterDeploymentListener(m, &deviceDeploymentRegisterDeploymentListenerServer{stream})
}

type DeviceDeployment_RegisterDeploymentListenerServer interface {
	Send(*DeviceDeploymentRequestEnvelope) error
	grpc.ServerStream
}

type deviceDeploymentRegisterDeploymentListenerServer struct {
	grpc.ServerStream
}

func (x *deviceDeploymentRegisterDeploymentListenerServer) Send(m *DeviceDeploymentRequestEnvelope) error {
	return x.ServerStream.SendMsg(m)
}

var _DeviceDeployment_serviceDesc = grpc.ServiceDesc{
	ServiceName: "autonomic.ext.deployment.DeviceDeployment",
	HandlerType: (*DeviceDeploymentServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RegisterDeploymentListener",
			Handler:       _DeviceDeployment_RegisterDeploymentListener_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "autonomic/ext/deployment/device_deployment.proto",
}
